### ISSUE TITLE
Web backend for enaml?

### ISSUE THREAD

**Issue by ts468** [nucleic/enaml#164]
Hi,

is there a chance that enaml will get a web backend to write web applications with it? That feature was mentioned in a talk last December, and I wondered if it is still on the roadmap?

Thanks,
Thomas

**Comment by frmdstryr** [comment]
@sccolbert any chance you could share the work that was started on this?  

Going back to django after working with Enaml for a while leaves a lot to be desired on django's side...

**Comment by KayLuke** [comment]
Enaml-web now exists. Should be a good place to start: https://github.com/codelv/enaml-web

**Comment by sccolbert** [comment]
That's fantastic!
