### ISSUE TITLE
Dialog widget doesn't have a layout initialized

### ISSUE THREAD

**Issue by vladwing** [nucleic/enaml#174]
There is an exception when trying to use a `Dialog` widget in ENAML. The problem seems to be [`self.layout()`](https://github.com/nucleic/enaml/blob/f72831f9b990dc62b02f75954e27693bef4eb68a/enaml/qt/q_window_base.py#L98) in `QWindowBase.setCentralWidget()` returns `None`.

While digging deeper, I discovered the problem in `QWindowDialog` inheriting from `QDialog` and `QWindowBase`. Somehow `QWindowBase.__init__` doesn't get called by `QWindowDialog.__init__`'s `super` call.

[Example code](https://github.com/nucleic/enaml/blob/master/examples/stdlib/message_box.enaml)
Using latest Enaml with PySide, on Linux

**Comment by MatthieuDartiailh** [comment]
Work on supporting for PySide2/6 have fixed this issue.
