### ISSUE TITLE
Severe crash in enaml 0.9, no crash in enaml 0.8.9. Certain features of PySide incompatible with certain features of Enaml?

### ISSUE THREAD

**Issue by jason-s** [nucleic/enaml#175]
I've had an issue with the newest versions of enaml crashing somewhere below the Python layer, so I don't get any stack trace, just a process crash.

This problem has been plaguing me for months, and has prevented me from upgrading beyond enaml 0.8.9. I have finally had time to pare my application down to a little test case that exhibits the problem, and here it is:

https://gist.github.com/jason-s/4a08f08afa3442bcba59

```
from PySide import QtCore
from enaml.qt.qt_application import QtApplication
 
class UI(QtCore.QObject):
    def __init__(self, **kwargs):
        super(UI, self).__init__()
        print "got here"
        self.app = QtApplication()
        print "didn't get here"
 
def setup(**kwargs):
    return UI(**kwargs)
 
if __name__ == '__main__':
    setup()
```

I am using Windows 7 + Anaconda Python. The files env_bad.txt and env_good.txt are the Anaconda environment files (from "conda list -e") that show the different versions of packages in the environment.

The "good" environment (env_good.txt) has these package versions:
atom=0.3.5=py27_0
enaml=0.8.9=py27_0

The "bad" environment (env_bad.txt) has these package versions:
atom=0.3.9=py27_0
enaml=0.9.8=py27_0
kiwisolver=0.1.3=py27_0
pyqt=4.10.4=py27_0

I will try to install an earlier version of enaml to help bound the problem.

**Comment by jason-s** [comment]
The Windows process-crash-error-message-box lists this:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	0.0.0.0
  Application Timestamp:	54935bff
  Fault Module Name:	QtGui4.dll
  Fault Module Version:	4.8.6.0
  Fault Module Timestamp:	53594eca
  Exception Code:	c0000005
  Exception Offset:	0000000000020102
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	c209
  Additional Information 2:	c209d20111349d9c68c99b23406952d1
  Additional Information 3:	b0f5
  Additional Information 4:	b0f57cad609b8a3eb161c93314d2ddaa

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by jason-s** [comment]
Interestingly, if I switch the order of the two imports, I don't get a crash:

```
from enaml.qt.qt_application import QtApplication
from PySide import QtCore

class UI(QtCore.QObject):
    def __init__(self, **kwargs):
        super(UI, self).__init__()
        print "got here"
        self.app = QtApplication()
        print "didn't get here"

def setup(**kwargs):
    return UI(**kwargs)

if __name__ == '__main__':
    setup()
from enaml.qt.qt_application import QtApplication
from PySide import QtCore

class UI(QtCore.QObject):
    def __init__(self, **kwargs):
        super(UI, self).__init__()
        print "got here"
        self.app = QtApplication()
        print "didn't get here"

def setup(**kwargs):
    return UI(**kwargs)

if __name__ == '__main__':
    setup()
```

**Comment by sccolbert** [comment]
PySide is not officially support because it's buggy (as you've found). There are already a bunch of pyside-related bugs which I don't plan to spend the time to fix. Just use PyQt.

https://github.com/nucleic/enaml/issues?q=is%3Aopen+is%3Aissue+label%3A%22PySide+bug%22

**Comment by sccolbert** [comment]
That said, you this is probably happening because you are mixing imports. Enaml will default to using PyQt if it's installed, and that will be imported as soon as you touch `enaml.qt`

**Comment by sccolbert** [comment]
if you want to use PySide, explicitly set the env flag `QT_API=pyside`

**Comment by sccolbert** [comment]
and as always, the source is your friend:
https://github.com/nucleic/enaml/blob/master/enaml/qt/__init__.py

**Comment by jason-s** [comment]
Ah. OK. I'll give it a shot, thanks!

**Comment by jason-s** [comment]
Switching to `QT_API=pyside` solves my problem, application now works OK with 0.9.8

(I looked at PyQt4 and though it might be more properly supported by enaml, my application is not easily made compatible with PyQt4.)
