### ISSUE TITLE
refactor QPopupView.mousePressEvent to allow proper intercept of click actions to do something else besides close

### ISSUE THREAD

**Issue by jason-s** [nucleic/enaml#176]
[https://github.com/nucleic/enaml/blob/f72831f9b990dc62b02f75954e27693bef4eb68a/enaml/qt/q_popup_view.py#L807](QPopupView.mousePressEvent) has some moderately complex logic to handle close on click. I want to hide on click rather than close on click, but there's no way for me to reuse this logic without reaching into the popupview/proxy/widget combination and doing a bunch of things.

    def mousePressEvent(self, event):
        """ Handle the mouse press event for the popup view.
        This handler ensures that the window is closed in the proper
        cases, when the superclass method doesn't handle it.
        """
        event.ignore()
        state = self._state
        if state.close_on_click:
            path = state.path
            pos = event.pos()
            rect = self.rect()
            win_type = self.windowType()
            if win_type == Qt.Popup:
                if not rect.contains(pos):
                    super(QPopupView, self).mousePressEvent(event)
                else:
                    path = state.path
                    if not path.isEmpty() and not path.contains(pos):
                        event.accept()
                        self.close()
            elif win_type == Qt.ToolTip or win_type == Qt.Window:
                if path.isEmpty() or path.contains(pos):
                    event.accept()
                    self.close()

Anyway to refactor this so `mousePressEvent()` does some action that, by default, does something like this:

    if state.close_on_click:
      self.close()

so it can be reused for other purposes like hide on click?

**Comment by sccolbert** [comment]
No. The contract of the `PopupView` lifetime is in the docstring:

```
    A PopupView is a single-use transient widget that is automatically
    destroyed when it is closed. It is useful for showing contextual
    popup dialogs or notification messages.
```

Why do you need to hide it instead of destroy it? If you are keeping all your state in a model (best practice), then you can just create a new instance of the view when you need it again.

**Comment by jason-s** [comment]
>Why do you need to hide it instead of destroy it? If you are keeping all your state in a model (best practice), then you can just create a new instance of the view when you need it again.

My program sometimes generates several events in quick succession. What I don't want is to generate a bunch of popupview windows on top of each other, and require the user to click them all away. So then I have  to keep track of something + handle the case where there is already a popupview dialog shown.

I'll take a crack at trying to refactor to use a new PopupView each time. It just seemed like it might be easier to create a PersistentPopupView widget, but the hooks aren't there in PopupView to subclass it in this way.

**Comment by jason-s** [comment]
How do you query a PopupView object to find out if it is closed?

**Comment by sccolbert** [comment]
Set the `timeout` to zero and use your timer or logic to manage when it should be destroyed.

You can check if a widget has been destroyed with the `is_destroyed` attribute.
