### ISSUE TITLE
Looper raise ValueError when assigning new items with twice the same object.

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#184]
The issue can easily be reproduced by modifying the looper example as follows : 
```
PushButton: button:
    text = 'Add Item'
    clicked ::
        items = field.text.split()
        items.append(items[-1])
        field.text = ' '.join(items)
```
It seems it tries to remove an old item that it already removed, I don't understand why...

**Comment by sccolbert** [comment]
The Looper assumes the items in the iterable are unique (this needs to be documented). It uses the assumption as an optimization to only create/destroy the widgets corresponding to items in the iterable which have changed: https://github.com/nucleic/enaml/blob/master/enaml/core/looper.py#L96

This makes it possible to loop over large'ish lists and not rebuild a ton of widgets when an item is added/removed/moved.

**Comment by sccolbert** [comment]
Fixed in 81a46b9b99bc9037fa67145ff61c703c3b2df3cf

**Comment by MatthieuDartiailh** [comment]
Thanks for the explanation I will just have to make sure that this does not happen then.

**Comment by sccolbert** [comment]
Alternatively, use an Include instead of a Looper. It doesn't have the same restriction since you manage the widgets to include yourself.

**Comment by MatthieuDartiailh** [comment]
That's fine, I saw the errors because I was allowing to copy an object and then paste it, potentially in the same list. I now use deepcopy when copying (which is saner) and the issue is gone, I was just worried because I had sometimes seen my app crash because of that error but never understood what was actually causing the crash.
Thanks again for the reactivity !

**Comment by sccolbert** [comment]
Be careful even with the deep copy. The internal map uses equality comparison, not object identity. So if one of your objects overrides `__eq__`, it may cause trouble. Just FYI.

**Comment by MatthieuDartiailh** [comment]
Thanks for the precision. In this particular case, I am safe but I will keep it in mind for other uses.
