### ISSUE TITLE
How to Read Arguments Passed to an Event Handler?

### ISSUE THREAD

**Issue by more-more-tea** [nucleic/enaml#185]
I'm designing a UI with Enaml in Python. I have a custom control containing , say two buttons. Each time any of the two buttons is clicked, one is 1 and the other id-ed 2, I want the parent container has a sense which one is clicked. So the event handler from parent accept an extra parameter distinguishing the source of the event. Here is my code

    from enaml.widgets.api import (
        Window, Container, PushButton
    )

    enamldef TwoButtons(Container):  
        attr cont
        PushButton:        
            text = 'Button1'
            clicked :: cont.clicked(1)

        PushButton:
            text = 'Button2'
            clicked :: cont.clicked(2)

    enamldef Main(Window):
        Container:
            attr buttonId
            event clicked

            TwoButtons:
                cont = parent

            clicked ::
                # A way to read the event handler argument goes here
                print "Someone is clicked, don't know who :("

Any suggestions?

**Comment by sccolbert** [comment]
Sounds like you figured it out:

http://stackoverflow.com/questions/29915502/enaml-get-arguments-passed-in-an-event-handler
