### ISSUE TITLE
Handle text changes when ComboBox / ObjectCombo is editable 

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#194]
ComboBox's and ObjectCombo's can be set to editable, but there is no event triggered to handle when the text is edited. Is there a way to do this?

Would it be possible to delegate handling to a child Field?

**Comment by sccolbert** [comment]
'editable' is a misnomer. What it does is really enable auto-complete on the combo box so you can type to select a value. It doesn't actually allow you to change the contents of the combo box.
