### ISSUE TITLE
Issues on closing window

### ISSUE THREAD

**Issue by licode** [nucleic/enaml#195]
I wrote a gui to open several other windows from a mainwindow. However, when I close the mainwindow, the already opened child-windows still exist. How can I close all of them at once?

I play the parameter like destroy_on_close, but it doesn't work.

thanks!

**Comment by sccolbert** [comment]
Use the main window as the parent of the child windows.

```
from enaml.widgets.api import *

enamldef Main(Window): main:
    Container:
        Label:
            text = 'Main Window'
        PushButton:
            text = 'Open Child'
            clicked :: Child(parent=main).show()

enamldef Child(Window):
    Container:
        Label:
            text = 'Child Window'
```
