### ISSUE TITLE
ObjectCombo : timer can fire after object destruction

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#199]
The timer in charge of collapsing the refresh requests is not stop when destroying and there is no guard checking that the declaration still exists when actually refreshing. This can cause an attribute error.

I can do a PR but I am not sure whether we can stop reliably the timer in the destroy method or to simply add a check in the refresh_items method.

**Comment by sccolbert** [comment]
You should be able to reimplement `destroy` on [QtObjectCombo](https://github.com/nucleic/enaml/blob/master/enaml/qt/qt_object_combo.py) and call `self.refresh_timer.stop()` (remember to call super destroy after stopping the timer).

If that works, feel free to open a PR.
