### ISSUE TITLE
Importing a module always populate sys.module even when import fails

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#202]
I noticed something that seems like a bug to me. When importing an enaml module causing an exception to be raised, the module is always added to sys.modules which is not the standard behavior of python. This means that if importing a module a first time and catching the exception, a second import will not raise but return an empty module.
This has bugged me for some hours when writing tests which were not raising the right error because the module was previously imported. I will open a PR in the coming days.

**Comment by sccolbert** [comment]
This will be method to look at:
https://github.com/nucleic/enaml/blob/master/enaml/core/import_hooks.py#L124

**Comment by sccolbert** [comment]
Yep. I should remove the module from sys.modules if it errors on exec. That's what the default importer does: https://github.com/python/cpython/blob/master/Python/import.c#L825
