### ISSUE TITLE
Cannot subclass FileDialogEx

### ISSUE THREAD

**Issue by bburan** [nucleic/enaml#204]
I cannot subclass FileDialogEx so that I can pre-set some of the fields (e.g., the file name filters) for a common file type. For example:

    enamldef LayoutFileDialog(FileDialogEx):
        name_filters = ['Workspace layout (*.layout)']
        selected_name_filter = '*.layout'

If I call this:

    LayoutFileDialog.get_save_file_name()

I still get the standard file dialog with no filters.

**Comment by sccolbert** [comment]
You don't need to subclass it. Just pass the attributes as kwargs:

`FileDialogEx.get_save_file_name(name_filters=[...], selected_name_filter='*.layout')`
