### ISSUE TITLE
Manually reparenting a container does reset the layout_parent member

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#206]
While playing with manually re-parenting a container to avoid destroying widgets, I noticed that a container when reparented the Qt backend does not reset the layout parent member. This can lead to crash on the next relayout as the parent will try to relayout and fail to do so as a child is missing. I think the fix should be in qt_constrainable but I would like an opinion before submitting a patch.

**Comment by sccolbert** [comment]
Yeah, there's a general issue with the Python Qt bindings which makes it difficult to change a layout. In C++, you must first `delete` the old layout, before you can apply the new one. The problem is that there is no way to synchronously `delete` the layout from Python, which means there's not a general way to change the layout.

Not sure exactly what code you tried, but I imagine the problem is related to this issue.

**Comment by MatthieuDartiailh** [comment]
I do not think the issue is from the Qt binding. Here is what I do.

I have a top most container (C1) in which I wan to display different widgets (based on user input). First I place an item (C2) with multiple children, enaml build the layout manager for this system and attribute a layout index and parent to every container children on my item. Then I take one of those children (C3) and reparent it to C1. A subsequent event lead to a request-relayout call (for example a Conditional condition change). C3 will execute that call but because set_parent did not reset the value of layout_parent it will also request the relayout of C2, which will fail because C3 is not longer of child of C2 (and the layout managr was not properly cleaned). This is all happening inside the enaml logic.

**Comment by MatthieuDartiailh** [comment]
@sccolbert any hope to get some feedback on https://github.com/nucleic/atom/pull/65 any time soon ?

**Comment by sccolbert** [comment]
Ah, okay. Any chance you could make a simple gist which reproduces the behavior? If it's a bug in Enaml logic, I'll see what I can do to fix it or give you a workaround.

**Comment by MatthieuDartiailh** [comment]
I will try to make a gist. A workaround it to manually set the proxy layout_parent member to None when reparenting.

**Comment by MatthieuDartiailh** [comment]
Here is a gist. To demonstrate the issue swith to C2 and click the button 'Add label'. You should get an index error, which can be tracked down to the realyour of C1 which should not occur. Properly unparenting C1 does not fix the issues. Deleting the layout parent on the proxy however does work. Hence my guess that this should be added to child_removed of qt_constrainable.
<script src="https://gist.github.com/MatthieuDartiailh/0db8fc2967f992c8bb2401618013c354.js"></script>

**Comment by MatthieuDartiailh** [comment]
Could you give this a quick look @sccolbert ? If you agree that this should be fixed in qt_constrainable I could make a PR.

**Comment by MatthieuDartiailh** [comment]
Closed by #240
