### ISSUE TITLE
Parser : function call f(a, b, *c, d=1) not supported

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#212]
That form of function call is supported even under python 2. I think it is a matter of adding the right couple of rule to the parser. I can do it this week end if nobody beats me to it.

**Comment by sccolbert** [comment]
yep, here's the relevant grammar for arglist:

```
arglist: (argument ',')* (argument [',']
                         |'*' test (',' argument)* [',' '**' test]    // <== relevant rule
                         |'**' test)
# The reason that keywords are test nodes instead of NAME is that using NAME
# results in an ambiguity. ast.c makes sure it's a NAME.
argument: test [comp_for] | test '=' test
```

**Comment by MatthieuDartiailh** [comment]
Thanks

**Comment by sccolbert** [comment]
Looks like these rules handle a portion of that case, but are missing the leading optional `arglist_list`:
https://github.com/nucleic/enaml/blob/master/enaml/core/parser.py#L3392-L3431

**Comment by MatthieuDartiailh** [comment]
Indeed I noticed that. About to open the PR.
