### ISSUE TITLE
ImportError when using QtMPLCanvas

### ISSUE THREAD

**Issue by fkohlgrueber** [nucleic/enaml#221]
**Problem Description**

An ImportError occurs when trying to use `QtMPLCanvas`:
```python
...
File "c:\dev_env\lib\site-packages\enaml\qt\qt_mpl_canvas.py", line 13, in <module>
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg
ImportError: cannot import name NavigationToolbar2QTAgg
```

**System setup**
- Windows 7
- Python 2.7.13
- enaml 0.9.8
- matplotlib 2.0.0

**Code to reproduce the error**

Just use the Enaml MPLCanvas example: [http://nucleic.github.io/enaml/docs/examples/ex_mpl_canvas.html](http://nucleic.github.io/enaml/docs/examples/ex_mpl_canvas.html)

**Cause of the error**

Matplotlib removed `NavigationToolbar2QTAgg` in version 1.5.0, see [here](http://matplotlib.org/devdocs/api/api_changes.html?highlight=navigationtoolbar2qtagg#remove-navigationtoolbar2qtagg)

**Discussion**

I tried to replace `NavigationToolbar2QTAgg` with `NavigationToolbar2QT` and this fixes the import error. I'm not sure though if this could break older versions of matplotlib.

If you want me to, I can write a pull request with the changes described above.

I'm looking forward to your feedback. Thanks in advance.

**Comment by MatthieuDartiailh** [comment]
I believe this is fixed in the new release, could you check ?

**Comment by fkohlgrueber** [comment]
I can confirm that the import is working with my current setup:

- Ubuntu 17.10
- Python 2.7.14
- PyQt 4.11.4
- enaml 0.10.1
- matplotlib 2.1.0

I'm closing the issue, thanks for fixing this.

**Comment by MatthieuDartiailh** [comment]
Thanks for taking the time to test !
