### ISSUE TITLE
Using Enaml for mobile apps

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#222]
I've been playing around with trying to use Enaml for creating mobile apps (see [enaml-native](https://github.com/frmdstryr/enaml-native)) in python using native widgets.  It is working, however loading enaml is awful slow (takes over 8 seconds on a Nexus 5) which is pretty much a killer for the whole concept.  

After some investigation this is due to the `yacc.yacc` call in [enaml/core/parser.py#L3984](https://github.com/nucleic/enaml/blob/master/enaml/core/parser.py#L3984) taking almost 8 seconds to complete. (There's also `jnius.autoclass` taking forever but I'm working on that as well)

```

05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:          1124963 function calls (1115859 primitive calls) in 22.236 seconds
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:    Ordered by: cumulative time
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:    ncalls  tottime  percall  cumtime  percall filename:lineno(function)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:        33   10.232    0.310   12.482    0.378 /data/user/0/com.jventura.pyapp/assets/python/site-packages/jnius/reflect.py:149(autoclass)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.000    0.000   11.285   11.285 /data/user/0/com.jventura.pyapp/assets/python/bootstrap.py:22(router)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.000    0.000   11.285   11.285 /data/user/0/com.jventura.pyapp/assets/python/bootstrap.py:33(handle)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.000    0.000   11.285   11.285 /data/user/0/com.jventura.pyapp/assets/python/bootstrap.py:100(start)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.008    0.008   11.285   11.285 /data/user/0/com.jventura.pyapp/assets/python/enamlnative/android/app.py:51(start)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.000    0.000   11.277   11.277 /data/user/0/com.jventura.pyapp/assets/python/enamlnative/android/app.py:60(get_view)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:      25/1    0.001    0.000   10.954   10.954 /data/user/0/com.jventura.pyapp/assets/python/site-packages/enaml/widgets/toolkit_object.py:147(initialize)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:        25    0.001    0.000   10.952    0.438 /data/user/0/com.jventura.pyapp/assets/python/site-packages/enaml/application.py:351(create_proxy)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:        25    0.000    0.000   10.951    0.438 /data/user/0/com.jventura.pyapp/assets/python/site-packages/enaml/application.py:325(resolve_proxy_class)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:        30    0.000    0.000   10.950    0.365 /data/user/0/com.jventura.pyapp/assets/python/site-packages/enaml/application.py:127(resolve)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:      25/1    0.001    0.000    9.258    9.258 /data/user/0/com.jventura.pyapp/assets/python/site-packages/enaml/core/declarative.py:103(initialize)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.022    0.022    8.264    8.264 /data/user/0/com.jventura.pyapp/assets/python/site-packages/enaml/__init__.py:36(imports)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.115    0.115    8.243    8.243 /data/user/0/com.jventura.pyapp/assets/python/site-packages/enaml/core/import_hooks.py:8(<module>)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.090    0.090    8.023    8.023 /data/user/0/com.jventura.pyapp/assets/python/site-packages/enaml/core/parser.py:8(<module>)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.005    0.005    7.719    7.719 /data/user/0/com.jventura.pyapp/assets/python/site-packages/ply/yacc.py:3214(yacc)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.001    0.001    6.869    6.869 /data/user/0/com.jventura.pyapp/assets/python/site-packages/ply/yacc.py:2100(__init__)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.690    0.690    6.523    6.523 /data/user/0/com.jventura.pyapp/assets/python/site-packages/ply/yacc.py:2533(lr_parse_table)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.000    0.000    3.958    3.958 /data/user/0/com.jventura.pyapp/assets/python/site-packages/ply/yacc.py:2509(add_lalr_lookaheads)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    1.812    1.812    1.816    1.816 /data/user/0/com.jventura.pyapp/assets/python/site-packages/ply/yacc.py:2283(find_nonterminal_transitions)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:     53114    1.332    0.000    1.804    0.000 /data/user/0/com.jventura.pyapp/assets/python/site-packages/ply/yacc.py:2163(lr0_goto)
05-26 12:30:49.509 19789-19789/com.jventura.pyapp I/pybridge:         1    0.007    0.007    1.696    1.696 /data/user/0/com.jventura.pyapp/assets/python/enamlnative/android/factories.py:103(drawer_layout_factory)
more excluded ...

```

Does enaml require the use of ply? Could some alternative be used? If not, I've been thinking about cythonizing ply, but before going that far I thought I'd check here and see if that would even work.

Thanks!

**Comment by tstordyallison** [comment]
At a glance - I'd say something is causing ply to regenerate its parse table (which is probably not that quick).

Somewhere in there I think it's meant to write down the parse table to disk (or you can generate it manually and save it with your code). I know our production deployment does that. We had to update it a few times when we changed our ply version too. Maybe there's a mismatch for you with the one that is already there?

Also, depending on how this is all glued together, you might not be generating enamlc files correctly. These are similar to pyc, and prevent the compiler from having to run altogether for a production app. I don't know if there's any tooling around to generate them in bulk for prod, we rolled our own for our somewhat custom setup... Be warned that many thousand line enaml files won't be quick to compile if you don't have a cache!

Tom

**Comment by tstordyallison** [comment]
(And, nice project by the way!).

**Comment by frmdstryr** [comment]
Ahh, actually you're right. The AssetExtractor is overwriting on each startup. Removed that and now it's only about 400ms. That's good enough for now.

**Comment by frmdstryr** [comment]
Thanks! Now to figure out how to speed up pyjnius...

**Comment by sccolbert** [comment]
@tstordyallison out of nowhere! Thanks!

**Comment by frmdstryr** [comment]
Actually to save me some time digging, can you share how to generate the parse table manually?

**Comment by sccolbert** [comment]
@frmdstryr That project is pretty dang cool!

**Comment by sccolbert** [comment]
https://github.com/nucleic/enaml/blob/master/enaml/core/parser.py#L3982-L3987

**Comment by sccolbert** [comment]
`yacc.yacc()` is more-or-less a no-op if the parse table already exists.

**Comment by sccolbert** [comment]
So basically, all you have to do is import `enaml.core.parser`, and it should generate the table.

**Comment by frmdstryr** [comment]
Thanks :). Hopefully I can figure out how to speed up pyjnius now. 

One more thing, do you know if the parse table is arch dependent at all?

**Comment by tstordyallison** [comment]
@frmdstryr I'm 99% sure it isn't - we use the same table on Windows and Linux.

**Comment by frmdstryr** [comment]
Alright good, hopefully I can just package them with the apk.  Closing now.

**Comment by sccolbert** [comment]
The parse table is just a python file filled with a bunch of lists and dicts.

**Comment by sccolbert** [comment]
Also what @tstordyallison mentioned about the `.enamlc` files is important as well. If you ship those, the parser will never even be invoked.

**Comment by frmdstryr** [comment]
Alright, I'll have to figure out how to create cache files that work with the specific platform. I was having issues with shipping cache files before so I just aborted (for times sake). Will have to revisit if it can speed up the startup time.

**Comment by tstordyallison** [comment]
@frmdstryr pyc (and enamlc, though it has a different header on disk) are really just blobs of marshalled python bytecode.

Should work fine whatever the platform (we ship the same pyc to Windows and Linux).

**Comment by frmdstryr** [comment]
Ok, I figured it out. It's recreating the files because the latest ply version is 3.10 and the parse_tab files (lextab and parsetab) included with enaml are from version 3.4. Updated the files to the 3.10 ones and it's working fine :+1:

**Comment by sccolbert** [comment]
Hmm. It should be saving the new ones if it regenerates them. Maybe ply is swallowing the exception if the write directory is read-only.

**Comment by tstordyallison** [comment]
@sccolbert sounds familiar - we had to regenerate them the last time we updated ply.
