### ISSUE TITLE
What is the scope of references in a looper?

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#223]
What is the scope of a references in a looper?  In the button clicked callback I have to assign an item and use `self.item`, instead of `li.item`.  Is there a better way of doing this?

```python
         Page:
        title = "ListView"
        ListView: list_view:
          items = list(Icon.PACK_FONT_AWESOME)
          divider_height = 0
          background_color = '#EEEEEE'
          Looper:
            iterable = range(20) #: MUST ALWAYS be > list_view.visible_count
            ListItem: li:
              VBox:
                padding = (10,5,10,5)
                CardView:
                  content_padding = (10,10,10,10)
                  HBox:
                    Icon:
                      text_size = 32
                      text << u"{%s}"%li.item
                    Spacer:
                      layout_width = '10'
                    VBox:
                      CardTitle:
                        text << "Card {}".format(li.index)
                      TextView:
                        text << li.item
                    Button: btn:
                      attr item << li.item
                      style = 'borderless'
                      text = "Test"
                      clicked ::
                            #: This does not work
                            # print("Clicked: {}".format(li.item))
                            #: This does
                            print("Clicked: {}".format(self.item))
```

Also, just want to say that enaml is awesome. Can't believe it's actually fast enough for a updating [scrolling ListView on a phone](https://youtu.be/2SrnjaXR4QM).

**Comment by sccolbert** [comment]
> Each iteration of the loop will be given an indenpendent scope which is the union of the outer scope and any identifiers created during the iteration.

https://github.com/nucleic/enaml/blob/master/enaml/core/looper.py#L19-L33

So the `li` identifier should be visible from within the `ListItem`, but not from outside of it, and not across iterations.

The clicked handler should work as you expect. It might be a bug.

**Comment by frmdstryr** [comment]
Well, I must had a typo, or indentation issue or something... but I tried it again and now I can access both li, and btn. I was getting 'li' not defined errors before. idk, computers suck sometimes haha.
