### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#229]
I think the readme doesn't capture the users attention in the 10 seconds a new user typically has to decide which may lead potential users away. 

@sccolbert  and @tstordyallison did some very helpful talks on enaml that show why it's better than pretty much every other python UI framework (and I'd argue other languages as well) in a few minutes. Could one of these be added to the readme (near the top show it shows up on mobile)? 

Ex.
[![Enaml](https://img.youtube.com/vi/ycFEwz_hAxk/0.jpg)](https://youtu.be/ycFEwz_hAxk)

There was a newer PyData talk on vimeo that covered more but it seems to have been deleted.. that video would be better if anyone knows where it it is. 

Maybe a list of videos would be good:

1. https://www.youtube.com/watch?v=G5ZYUGL7uTo
2. https://www.youtube.com/watch?v=ycFEwz_hAxk
3. https://vimeo.com/79536617 (now a dead link...)

You can add a youtube thumbnail using `https://img.youtube.com/vi/<video id>/0.jpg` for example `[![Enaml](https://img.youtube.com/vi/ycFEwz_hAxk/0.jpg)](https://youtu.be/ycFEwz_hAxk)` (not sure how to do it with rst).

**Comment by tstordyallison** [comment]
(@frmdstryr thanks for the callout!)

**Comment by MatthieuDartiailh** [comment]
I will try to look into it but I don't know when. If anybody has time to do a PR he is welcome.

**Comment by frmdstryr** [comment]
@MatthieuDartiailh  or @sccolbert  could one of you please create a [gitter](https://gitter.im/home#createcommunity) (or some other discussion room) for enaml? I tried making https://gitter.im/nucleic/ but can't as I don't have access to the repo.

**Comment by MatthieuDartiailh** [comment]
I could but I am pretty sure I won't have time to participate in it... we already have a mailing list, is it not good enough ?

**Comment by frmdstryr** [comment]
I just thought it'd be a more informal way to get/give help. Just a suggestion, if you think it's not needed that's fine.

**Comment by MatthieuDartiailh** [comment]
I am mostly worried about people never getting any answer, which does not make a good impression.
