### ISSUE TITLE
NameError _[tracer] when using lambda with << operator

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#241]
This reproduces it.
```

from enaml.widgets.api import Window, Container, Label, PushButton, ProgressBar
from enaml.application import timed_call

enamldef Main(Window): main:
    Container: container:
        attr colors = [(3,'red'), (1, 'blue'),
                       (4,'yellow'), (2, 'green')]
        
        #: Works with = not <<
        attr sorted_colors << sorted(colors, key=lambda x:x[0])
        Label:
            text << '{}'.format(colors)
        Label:
            text << '{}'.format(sorted_colors)
        
        #: This works fine, just wanted to make sure
        ProgressBar: pb:
            value = 0
        PushButton:
            text = "Test"
            clicked ::
                #: Simulate some network event that takes time
                pb.value = 0
                timed_call(500, lambda pb=pb:setattr(pb,'value',50))
                timed_call(1000, lambda pb=pb:setattr(pb,'value',100))
```

Traceback

```
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/expression_engine.py", line 186, in read
    return pair.reader(owner, name)
  File "/home/jrm/Workspace/enaml/venv3/lib/python3.5/site-packages/enaml/core/standard_handlers.py", line 101, in __call__
    return call_func(func, (tr,), {}, scope)
  File "tests/examples/search.enaml", line 15, in <module>
    attr sorted_colors << sorted(colors, key=lambda x:x[0])
  File "tests/examples/search.enaml", line 15, in <lambda>
    attr sorted_colors << sorted(colors, key=lambda x:x[0])
NameError: name '_[tracer]' is not defined


```

**Comment by MatthieuDartiailh** [comment]
This basically means that we need to change the way we call the lambda to use call_func and pass the namespace. We need to do that because the body of the lambda may reference some part of the enamldef. I will look into it.

**Comment by MatthieuDartiailh** [comment]
One issue is that this somehow opens the door to defining function which is not allowed because we cannot guarantee that they will be called with the proper namespace. Should we disallow lambda, like we forbid function definitions ? @sccolbert WDYT ?

**Comment by tstordyallison** [comment]
For those of us rather rather large codebases, disallowing lambda is rather a harsh breaking change... it could be done, but it would make upgrading harder. I’d be surprised if we didn’t have usage of it already in various places.

I’d almost rather the tracer/scope just didn’t work inside the lambda (though having it work would be neat too!).

**Comment by sccolbert** [comment]
We're basically getting at my second concern from the previous issue. We need to make sure that each nested block, whether from a comprehension or lamba or whatever, is invoked with the proper semantics/scopes. The non-triviality of this is why I didn't implement it in the first place.

**Comment by sccolbert** [comment]
Forbidding lambdas at this point is a non-starter, since so much code out there already uses them.

**Comment by MatthieuDartiailh** [comment]
For comprehension the issue is simple since the function cannot leak out. For lambda the difficulty is that they can. Could we do something smart using closures ? In the meantime I will try to fix the unwanted injection of tracing inside them.

**Comment by MatthieuDartiailh** [comment]
#242 provides a short term solution that means that existing code won't break. If we want a full support of lambda we still have more work to do.

**Comment by frmdstryr** [comment]
Working now thanks.

**Comment by MatthieuDartiailh** [comment]
You are welcome
