### ISSUE TITLE
Prioritize subscription handlers

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#244]
This is not really an issue, more of a feature request based on some errors discussed in #238.

Would it be difficult to add some way of prioritizing handlers? Perhaps using a syntax similar to how the constraints lets you apply `: 'weak'`, `:'strong'`, etc... But instead either a number or a priority string (ex `:'high'`, `:'low'` etc..). 

I can think of several cases that would benefit from this.  One being the case when a layout depends on the nodes already existing in the tree (as in #238) and another being nodes within a `Conditional` block.

```python
    #: Set the initial layout
    layout << AreaLayout(
        TabLayout(*editor_items(plugin.documents)),
        #etc...
        ],
    ) : 'low'

    Looper:
        iterable << plugin.documents : 'high'
        DockItem:
            attr doc = loop_item

```
In this case the looper should always fire before the layout is updated. 

another case that I commonly use

```python

Conditional:
   condition << model.data is not None : 'high'
   Label:
       #: It makes sense that this handler only fires when the condition is true
       #: but it's possible if model.data is later set to None that this handler
       #: fires first (leading to a missing attribute) thus every handler within the
       #: conditional requires it's own check to make sure the data is still valid
       text << "{}".format(model.data.result) 

```

I don't know how complicated it would be. At a minimum I can see that atom would require an optional `priority` argument when `observe` is called (and a priority queue for the observer pool). Then if the compiler could see a priority is given it would need to pass it to every observe call in https://github.com/nucleic/enaml/blob/master/enaml/core/standard_tracer.py#L127.

Is this feasible?

**Comment by tstordyallison** [comment]
So - a confession - this is something we have in our build today (as an optional thing globally, but with the intent of it being always on).

It's called 'strict order' bindings. We ensure that if multiple traced expressions observe the same model attribute that they always fire in 'visual tree order'. We also take into account that Patterns (Conditional etc) are really siblings and adjust their 'ranking' in the tree. 

We found for complex UIs this was pretty much mandatory to stop them from going wonky. The performance wasn't ever ideal, so it never got switched on across the board. You have to book-keep for every subscription to keep them in order, and more or less re-implement the Atom observer pool. 

------

Also, I have some attachment to the `:` syntax above - we also have that mean 'the default value' in our build, as we have support for asynchronous bindings (for remote data models or calculations that take some time). 

Time willing, I do want to get some of this merged back in - as a company we are starting to be much more open to contributions externally. But as ever, they take time and other things take priority.

**Comment by tstordyallison** [comment]
Also, your point RE the layout/constraints is something we don't do as part of the 'strict ordering' mode, but come to think it, we could.

**Comment by frmdstryr** [comment]
Perhaps something simpler like a different operator could be used to indicate priority. This comes to mind:

```python

SomeWidget:
    text_low <{9} "Low (default) prio"
    text_med <{5} "Med prio"
    text_high <{1} "Higher prio"
    #: or maybe
    text_alt <<< "Something" # But I think the << operator would catch this
```
Or something along those lines. This would also be easier to implement as it wouldn't require any compiler changes. Simply adding a new operator that passes a priority to the [operator](https://github.com/nucleic/enaml/blob/master/enaml/core/operators.py#L185).

**Comment by frmdstryr** [comment]
Also, I had initially thought about using the order in the tree to determine which fires first but thought that would be much more complicated to implement (as it requires what you mentioned).    

If a priority can just be passed somehow it achieves the same thing but doesn't require any book keeping (unless I'm missing some use case?).

**Comment by sccolbert** [comment]
My opinion on this along the lines of "If you care about the order of subscriptions firing, you're doing something wrong". i.e. when the view logic gets so complicated that you start to depend on subscription firing order, then you should probably refactor some of that logic into a view model.

In the first case above, using an `Include` instead of a `Conditional` would solve the problem because only the include would have the dependency on `model.data`.
