### ISSUE TITLE
ENH: add justification options (right, center, etc.) in a Field

### ISSUE THREAD

**Issue by jason-s** [nucleic/enaml#248]
All Field objects appear to be left-justified only. I'd like to request adding right- and center-justified options for Fields.

Right-justification is important for visual alignment of numeric values.

**Comment by MatthieuDartiailh** [comment]
This should be quite straightforward to do. One question @sccolbert should the corresponding member be alignment or text_alignment for the sake of being fully explicit ?

**Comment by sccolbert** [comment]
We can support this by either adding a new attribute to the `Field` class, or supporting `qproperty-*` attributes in stylesheets, which would allow you to specify `qproperty-alignment` in a stylesheet.
https://forum.qt.io/topic/10695/qlabel-text-align-wit-stylesheet

**Comment by MatthieuDartiailh** [comment]
Do you have a preference for one option or another ?

**Comment by sccolbert** [comment]
It's probably better for alternate backends to have it as an attribute on the `Field` class, as I doubt any of the existing alternate backends are supporting stylesheets.

As an attribute, I would use `text_align` or `text_alignment`. I would choose between the two by grepping the code base and seeing whether I tend to use `align` or `alignment`.

**Comment by MatthieuDartiailh** [comment]
Ok will try to get to it before Christmas. Save if somebody beats me to it.

**Comment by sccolbert** [comment]
Fixed in #249
