### ISSUE TITLE
Windows menu on OSX are not working.

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#257]
The menu used for an application top level window (for example one built using the workbench) do not respond to click under OSX. There is perhaps something to tweak in term of event connection on the Qt side. As I do not have access to an OSX machine, help is welcome.

**Comment by gabrielcnr** [comment]
Do you have a minimal example of the bug?

I can take a look as I'm a Mac OS X user.

**Comment by MatthieuDartiailh** [comment]
Will try to make one.

**Comment by MatthieuDartiailh** [comment]
Thinking about it the workbench example should demonstrate the issue, and if it does not it will be interesting since I first encountered in an application using the workbench.

**Comment by MatthieuDartiailh** [comment]
I managed to borrow the mac of a colleague and it turns out this is a focusing issue (the menubar works after defocusing/refocusing the window). It appears to be a more or less known Qt issue that is fixed in 5.10. As a consequence I will close.
