### ISSUE TITLE
"Edit on GitHub" link broken on ReadTheDocs

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#264]
Steps to reproduce:

* Visit any page in the docs - e.g. [the Welcome page](http://enaml.readthedocs.io/en/latest/index.html)
* Find the "Edit on Github" link in the top right corner, and click on it.
* You are taken to [a blank page](https://github.com/nucleic/enaml//master/docs/source/index.rst) that just says "Not found".

Note the URL is (for example): `https://github.com/nucleic/enaml//master/docs/source/index.rst`.

The double backslashes should have "tree" or "blob" or something between them.

**Comment by MatthieuDartiailh** [comment]
I have seen since on other repos too, so I wonder if it might be an issue with RTD or perhaps they change something. If you have time to investigate and find something, let me know.

**Comment by Julian-O** [comment]
I found [this issue on Read The Docs](https://github.com/rtfd/readthedocs.org/issues/3203).

It claims the bug has been patched, and that a simple rebuild will fix the documents. I assume that's something a maintainer needs to do. (I have never used Read The Docs myself.)

**Comment by MatthieuDartiailh** [comment]
I rebuilt the docs and this is now fixed.
