### ISSUE TITLE
Menu shortcuts available even when menu isn't.

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#268]
[I am not sure if this is an Enaml issue or a QT issue, sorry.]

If you create a menu with an action that has a keyboard shortcut, that keyboard shortcut is active and will trigger the action *even when the menu is not enabled*.

The shortcut should only be enabled when the menu is enabled.

This sample code demonstrates the problem:

```
from enaml.widgets.api import \
    Action, CheckBox, Container, Label, MainWindow, MenuBar, Menu

enamldef MenuExptWindow(MainWindow): main:

    attr menus_on = False

    MenuBar:
        Menu:
            visible << bool(main.menus_on)
            enabled << bool(main.menus_on)
            title = '&Menu'
            Action:
                text = "Item\ti"
                triggered :: print("Item menu triggered")

    Container:
        CheckBox:
            clicked :: main.menus_on = not main.menus_on
            text = "Activate menu?"
```

Press "i" to trigger the printing of a message. It should only print a message if the checkbox is enabled.

Tested on both PyQt5 5.9 and PySide2 5.9.0a1.

**Comment by sccolbert** [comment]
Interesting. Qt manages the shortcuts, so I'm inclined to think it's a Qt issue. But, there may be something extra I need to do on the Qt side which I'm not currently doing.

**Comment by sccolbert** [comment]
According to these docs: http://doc.qt.io/qt-5/qaction.html

> When an action is disabled, it is not possible to trigger it through its shortcut.

So, this shouldn't be possible.

**Comment by sccolbert** [comment]
Oh! I just read your code more carefully.

You need to set the `enabled` flag on the `Action`, not the `Menu`.
