### ISSUE TITLE
Make Readme more welcoming

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#270]
[This is an opinion-based suggestion, so I didn't want to just go ahead and change it without some support. I hope this will be taken as it is intended - a helpful suggestion, not a whine.]

The README.rst file is the first thing that potential new users see. I think there is an opportunity to improve it to make it more welcoming.

* Mention the main platforms it is supported upon. If I am targetting windows, I want to see the word *Windows* explicitly stated. Ditto for OSX and Linux. I want to know which platforms are "supported" and which are actively tested upon.

* The photo of the presenter should be dropped.
    * It is unlabelled. Who is it? [I figured it out - @sccolbert.]
    * It suggests the project is about this personality. I think it appears more egotistical to the reader than was intended.
    * It isn't the first thing I want to learn about before deciding to install.
    * If you are still keen to keep it, but it in the section about talks, and put some examples up the top.

* The examples aren't compelling.
   * The dock items example may show something useful, but it isn't very attractive. Not a good first impression.
   * The Employee Record is better - it gives a firm idea of what is easily achievable.
      * Is there are reason the date field is a spinbox? Doesn't seem a good way of entering dates.
      * Is there a reason the age field is 0? The fact that the age field can be automatically kept up to date with the DOB declaratively is one of the features of Enaml I love.
      * What would be compelling is three copies of this screenshot - from Windows, OSX and Linux, showing you can write once and run across platforms, while looking native.
    * The Button Ring is a cute hack, but not something to attract users to say "Oh, that would be useful."
    * Consider a snippet of (particularly self-documenting) example code. That's what I want to see.

* Explicitly link to the installation instructions and getting started instructions. That is something I need early.

* I understand why there isn't a current version number included directly in the RST, but is there a way to make it a badge or something, because it would be good to know.

**Comment by frmdstryr** [comment]
Also just want to chime in and mention that the video wasn't added by @sccolbert, it was suggested by me to make it easier for newcomers to see why they might want to use enaml over just python and some widget framework.

My initial thoughts when I looked at enaml was that it was stupid to create a language extension vs just using python bindings to gtk/wx/qt, or a gui builder.. (as I had done for years prior). Despite this, I tried some examples and quickly realized the exact opposite was true, it was genius. It wasn't until several months after using enaml that I found this talk explaining some of the cases that can't be handled by python alone and _why_ it was necessary to build enaml.  I thought that adding the video in the readme would help others get up to speed more quickly.


- It'd also nice to have a "built with enaml" wiki page or something to show what users have made with enaml to show that it's more than capable of building non-trivial gui's.

**Comment by deepankarsharma** [comment]
Wonder if we can somehow convince some of the (many) industrial users to give testimonials / share screenshots?

**Comment by Julian-O** [comment]
Thanks all.

I'll work on a PR to deal with the simpler items first.

Do we have access to (and permission to take from) the slide-deck from @tstordyallison's Pycon talk? Some of the slides (e.g. at 2m43) seem to be perfect to explain some key concepts.

@sccolbert: I understand your point about demonstrating functionality. I think I will try to add some explanatory text to the examples to justify them.

However, I am a little weak on the Button Ring example. This demonstrates the constraint-based layout engine is perfectly willing to place a button on top of another button. At first glance, that seems closer to a con than a pro. Why is this a good thing?

Also, the example code explains this wouldn't be possible with a simple layout system. Why would this be impossible with a simple layout system? Couldn't you specify the exact co-ordinates of each button?

(Again, I hope my tone conveys genuine curiosity, wanting to understand how best to portray this to other newbies like myself, rather than sounding like an attack.)

**Comment by Julian-O** [comment]
I've made a PR to tackle several of these, but more to go.

How do people feel about linking to StackOverflow? I don't want to split the community from Google Groups, but SO is pretty much the standard/behemoth Q&A site for programmers, so it makes sense.

**Comment by MatthieuDartiailh** [comment]
I agree about SO, but I know that I usually do not follow the threads there while I try to answer questions asked on the Google group. @frmdstryr do you answer on SO ?

**Comment by frmdstryr** [comment]
I do, but I wasn't checking regularly, so some questions didn't get answered until several months later.

I just subscribed to the `enaml` tag so I should get notifications within a day now.

**Comment by Julian-O** [comment]
Okay, I have submitted PR #271.

What I did do:

* Substantial rewrite to the introduction/benefits section
* Mention the platforms.
* Explicitly linked to the installation instructions and getting started instructions.
* Added photos for both presenters, but made them thumbnails and in the talks section. Labelled the presenters with their names.
* Added shield showing the current version (in PyPi)
* Added link to Stackoverflow.
* Added link to license info
* Merged Help and Learn More sections.
- Examples
   + Put more context around them.
   + Re-ordered them.
   + Replaced the screen shot of the docks item with one showing the colours. (Won't appear until next push to ReadTheDocs.) 

What I didn't do:

- Didn't include illustrative side-by-side of what procedural versus declarative code looks like.
- Button Ring example
  + Explanation could be improved, but my understanding is still limited.
- Employee Example:
  + Didn't get screenshot from three platforms. I don't have access to macOS.
  + Didn't attempt to debug the Employee age being zero.
  + Didn't touch the spinbox for date selection, because it appears that *is* the Qt dateselector. Bit tongue.
- Shields
  + Didn't add Python versions supported shield. This info isn't in setup.py, so PyPI doesn't know about it.
  + Didn't add license shield. This info wasn't in setup.py at the last release, so PyPI doesn't know about it yet. It has been added, so PyPi might know after next release.
  + Didn't add StackOverflow shield. Tried it, but the shield was too unreliable.
- Didn't include industry testimonials or "built with" images.
