### ISSUE TITLE
PyQt GPL "infecting" even when using PySide backend

### ISSUE THREAD

**Issue by kiwi0fruit** [nucleic/enaml#276]
There happened a useful [conversation on Reddit](https://www.reddit.com/r/Python/comments/8rpg23/pyappshare_cookbook_for_creating_crossplatform/) about publishing python apps that depend on PySide and MIT/BSD wrappers around PySide/PyQt like qtpy/pyqtgraph/matplotlib. [Backup of the discussion](https://github.com/kiwi0fruit/pyappshare/files/2110002/pyappshare_reddit.zip).

According that conversation there are concerns that using qtpy/pyqtgraph/matplotlib in the propriate app even with PySide backend may lead to GPL violation.  The problems came from two points:

* even trying to import from PyQt may lead to the GPL "infecting",
* even having PyQt as a dependency may lead to the GPL "infecting" (so that pip/conda installation would install pyqt automatically).

After all the discussion on Reddit the best way to solve the problem seems to do that upstream: make sure that there is a reliable switch in the qtpy/pyqtgraph/matplotlib modules that effectively and reliably turns the app that uses them (app as a whole) to something like:

```py
if False:
    import PyQt
```

Maybe such switch is already there - but this needs checking. It's also would be great to unify that interface among modules.

And also remove PyQt from their dependencies so that they do not auto-download PyQt (I guess most of them already behave this way).

**UPD**

Quote about PyQt deps that are in some MIT/BSD modules:

> If it's not a bug then it's a missing (or unused) feature.
>
> I'm not as familiar with conda's own feature set, but given that these are pip installable packages, the upstream packages shouldn't declare PyQt (or PySide) as requires, but as extra_requires, and then downstream can decide to use install_requires to ensure that the they've got the GPL or LGPL GUI code of their choice. Really no package maintainer should ever include GPL code in requires without their own code being expressly GPL licensed, and that being their clear intent. If upstream packages are correctly using extra_requires and an automatic download is still being triggered then something has incorrectly set PyQt as an explicit or implicit requirement, and there's the bug.
>
> Again though an automatic download onto the end user machine without use is something that very likely should be fixed upstream, but most likely could pass muster as an unintentional at best infringement with no meaningful impact. It's the use that implicates the GPL. The one exception is when the incidental and unused download is then bundled into a distributed artifact (like a wheel or frozen exe), because now you're distributing the GPL'd code with your own.

**Comment by sccolbert** [comment]
Downloading PyQt (i.e. simply having it on your system) does not cause a GPL infection.

`qtpy` allows you to choose which api you want to use via an environment variable:
https://github.com/spyder-ide/qtpy/blob/master/qtpy/__init__.py#L104

The only time that choice is *not* honored, is if another Qt api has *already been imported*.

**Comment by kiwi0fruit** [comment]
I hope that you are right. But enaml dependence on PyQt might be a
redistributing of GPL code.

вт, 19 июня 2018, 23:58 S. Chris Colbert <notifications@github.com>:

**Comment by kiwi0fruit** [comment]
I guess depending on PyQt might be the same as distributing. Not importing
and using, but distributing - because installing enaml means installing
PyQt.

ср, 20 июня 2018 г., 0:27 S. Chris Colbert <notifications@github.com>:

**Comment by sccolbert** [comment]
That depends entirely on how you install enaml. No one forces you to use pip or conda. Enaml doesn't distribute PyQt. It's a non-issue. Full stop.

**Comment by kiwi0fruit** [comment]
There's no concern about depending. The end-user can set a configuration
that can never import from PyQt. But any configuration with enaml means
that PyQt is installed - hence PyQt code is distributed. The knolegseble
man thinks that at most it can lead to court prescription to fix this issue
so that that GPL is not violated (in case of propriate license) - that's
really a minor issue - but still it's not comfortable to violate GPL or
repackage BSD enaml only for not depending from GPL.

ср, 20 июня 2018 г., 2:19 Peter Zagubisalo <peter.zagubisalo@gmail.com>:

**Comment by sccolbert** [comment]
> But any configuration with enaml means that PyQt is installed - hence PyQt code is distributed

That's simply not true. You can roll your own pip or conda package from source, and not install PyQt. Further, Enaml isn't a package manager, so we're still not distributing PyQt, no matter which way you try to say it.

I'm locking this conversation, and won't be making any changes.
