### ISSUE TITLE
"future" module dependency: Installation instructions versus setup.py

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#278]
The installation instructions say that there is a dependency on the [`future`](https://pypi.org/project/future/) module. Indeed there are several references to `from __future import [...]` in the code.

However, the `setup.py` file has no mention of it. The `.travis.yml` file has no mention of it. And yet the tests are passing.

If it is necessary to install the `future` module, `setup.py` should be fixed to include it, and there should be some test that demonstrates the need for it.
If it is not necessary to install the `future` module, `installation.rst` should be fixed to exclude it.

**Comment by MatthieuDartiailh** [comment]
At one point we were relying on `future` but @frmdstryr submitted a patch to avoid it (because it is slow), so we need to update installation.

**Comment by Julian-O** [comment]
Great. I have a pull request on installation right now- #277. I'll bundle this in.
