### ISSUE TITLE
Support for f strings

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#286]
Python 3.6 introduced f-strings, which are not yet supported in enaml. Adding support for them requires:
- updates to the parser
- checking that f-strings work as expected in subscription observers
- writing tests

The first point complexity may be mitigated by relying on ast.parse to the f-string since we know that the string cannot contain anything enaml specific. The second point should be simple also since when looking at the disassembly, the bytecode is not special and the current analysis should work.

**Comment by frmdstryr** [comment]
@MatthieuDartiailh Are you working on this?  I don't want to duplicate the effort, but if you're not, I'll give it a shot.

**Comment by MatthieuDartiailh** [comment]
f-strings are 3.6+ only. I would prefer to stick with them there honestly.
