### ISSUE TITLE
Python 3.7 support 

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#287]
Full support for Python 3.7 requires to at least check the following items:
- [x] make sure we treat async/await are treated as full keyword (PR #281)
- [x] check the impact of LOAD_METHOD and CALL_METHOD new opcodes
- [ ] make sure both Travis and Appveyor do run the tests on Python 3.7 (conda sometimes downgrade to 3.6)

**Comment by MatthieuDartiailh** [comment]
This is blocked by atom support for 3.7

**Comment by odinlake** [comment]
enaml/enaml/core/byteplay/byteplay2.py contain raise statements that are not valid py3. I noticed this in the output of "setup.py install" while it was extracting a .egg.

**Comment by MatthieuDartiailh** [comment]
This can be safely ignored since this file is not used under Python 3. Actually the last release of enaml support and is tested under Python 3.7, I just forgot to close that issue and mention it in the release notes !
