### ISSUE TITLE
enaml-run needs .enaml extension provided - contradicting documentation.

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#293]
Throughout the example documentation, there are command lines provided explaining how to run the examples.

e.g. the [H Group Example](http://enaml.readthedocs.io/en/latest/examples/ex_h_group.html)

> $ enaml-run h_group

None of these command lines include the `.enaml` extension to the files.<sup>1</sup>

When you run these commands, they give an error:

> FileNotFoundError: [Errno 2] No such file or directory: 'h_group'

(This is the case on Windows, and consulting the code, it looks like it would do the same thing on Linux.)

Either the manual should be updated to include the .enaml extensions throughout the documentation, or `enaml-run` should be updated to try the .enaml extension if the first filename is not present.

<sup>1</sup>There is one exception - the Hello World tutorial includes the `.enaml` extension.

**Comment by Julian-O** [comment]
If someone does edit the examples, a small bit of standard text above each command line would help - the command line kind of sticks out with no context.

**Comment by MatthieuDartiailh** [comment]
I guess I never noticed since I usually rely on the console auto-completion. I believe updating the docs would make more sense. If you have time you pack it with #294.
