### ISSUE TITLE
__file__ attribute is incorrect in Enaml files.

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#295]
[This is a roundabout journey, but I get to the problem in the end.]

If you run `make examples`, it calls `example_doc_generator.py`. That script makes a copy of each example .enaml file into the docs directory, imports it, runs it, and takes a snapshot image for the documentation.

It fails to get a snapshot of `tool_buttons.enaml`. 

Why? Well `tool_buttons.enaml` needs some supporting files to run - some images. It loads those from a directory relative to the source file:

    dirname = os.path.dirname(__file__)
    fname = os.path.join(dirname, 'images', '%s.png' % name)

When the single .enaml file is copied to a new directory, it doesn't copy the images too, and so it fails.

Okay, so I had a stab at fixing this. I figure the only reason `example_doc_generator.py` is copying .enaml files is so that it finds them on the path. So, I remove the code that copies it, and instead add the source directory to the `sys.path`, so the import function can find them in their original location, even though it isn't the current directory.

That seems to work very well.... except that it still fails to get a snapshot of `tool_buttons.enaml`!

Why? Well, the .enaml file is still running the above code, but `__file__` is still pointing to the current/docs directory - and there is no copy of the file there. That is bizarre!

It becomes clearer when it turns out the __file__ attribute is being set in `import_hooks.py`

    mod.__file__ = path

Sure enough, if I add an assert to import_hooks.py:

    mod.__file__ = path
    assert os.path.exists(path), path

it crashes out, complaining the path being assigned to to the file is the current directory, and not the actual source.

This is the point where I tap out, and say: I don't know what import_hooks is doing to determine the path, but it is incorrect, and that is causing `tool_buttons.enaml` (as one example) to fail when the current directory doesn't match the location of the .enaml file.

**Comment by MatthieuDartiailh** [comment]
Thanks for the report. I will try to look into it but it may take a few days.

**Comment by Julian-O** [comment]
Found the cause. There was a leftover enamlcache directory which I didn't know about (or understand).  The importer was finding old copies of the module in it.

The example generator normally deletes it - except that it was aborted halfway through.
