### ISSUE TITLE
Is there a way to use QIcon?

### ISSUE THREAD

**Issue by zenchanhk** [nucleic/enaml#301]
Hi everyone,

I'm new to `Enaml` and `PyQt5`, I'm wondering if there is way to use Iconic font in `Enaml`? I've found a project `QtAwsome` has done the work for `PyQt`. But the problem is `QtAwsome` return a `QIcon`, which cannot be used by Enaml, which requires binary bytes. Any Suggestions? 

Besides, I have tried the following convert but no luck.

```
    fa_icon = qta.icon('fa.flag')
    image = QImage(fa_icon.pixmap(20,20).toImage())
    ba = QByteArray()
    buffer = QBuffer(ba)
    image.save(buffer)
    return ba.data()
```

**Comment by MatthieuDartiailh** [comment]
Hi, I have used the following ugly workaround in some other projects:
```python
from qtawesome import icon as qicon
icon = enaml.icon.Icon(_tkdata=qicon('fa.' + icon_id))
```
I have not yet though of a better way to integrate this with enaml.

**Comment by sccolbert** [comment]
That's probably the simplest way to make it work without an internal change
to Enaml.

**Comment by MatthieuDartiailh** [comment]
I will close even though it would be nice to come up with a better scheme.

**Comment by zenchanhk** [comment]
@MatthieuDartiailh sorry for bothering you again. Is it possible to work with `QSvgRenderer`?

**Comment by MatthieuDartiailh** [comment]
What do you want to do with it ?

**Comment by zenchanhk** [comment]
I have a lot picture in `svg` format, and i want to put them in status bar to indicate the status.
