### ISSUE TITLE
Example tutorial/employee has non-functional feature/code

### ISSUE THREAD

**Issue by nasefbasdf** [nucleic/enaml#305]
In the main "employee.py" module at line 80 there is a method that is supposed to be a callback on a field change (like an observer), but it is not called by Atom. It could be an obsolete example to a previous observe mechanism, but I can't confirm that.

Is it supposed to work like that today?

[https://github.com/nucleic/enaml/blob/master/examples/tutorial/employee/employee.py#L80](url)

**Comment by sccolbert** [comment]
Good catch. That should be changed to `_observe_phone`. Good first issue if you're up for it.

**Comment by nasefbasdf** [comment]
I've made a pull request (#306) but it became a separate issue, so I'm closing this.
