### ISSUE TITLE
PySide2 support

### ISSUE THREAD

**Issue by kiwi0fruit** [nucleic/enaml#309]
Will there be PySide2 support as it was recently added to pypi? Now Enaml works with PySide2 but some bugs resemble the ones from PySide1 but I think error messages now different. So bugs may now be from PySide2 / PyQt differences not from PySide bugs. For example see this error message: https://github.com/nucleic/enaml/issues/108#issuecomment-418265842

**Comment by bburan** [comment]
Given that PyQt6 and PySide6 are out now and the age of this issue, I would argue for closing this as won't fix. It's a lot of work to support multiple backends and no one has stepped up to take ownership of this.

**Comment by MatthieuDartiailh** [comment]
Actually Pyside2 has been supported for at least a couple versions (I do lot remember from the top of my head when I did it). I must have missed this issue then.
