### ISSUE TITLE
Clarify: Signal Slot mapping in threaded operations?

### ISSUE THREAD

**Issue by achennu** [nucleic/enaml#313]
Great library, beautiful design. I've been trying to get my head around one concept, but the lack of documentation in the atom project has left me puzzled about a few things. I hope somebody here can point out the way, as it has as much to do with its use in GUIs as it has to do with observables.

I have some model objects, on which a user can trigger an asynchronous operation (threaded). The running worker thread should signal the percent completed (or other info) back to the GUI thread. In the PyQt world it is clear enough: don't access widgets from anywhere except GUI thread. But with enaml, when the worker thread updates an observed/observable member, then it triggers updates in the GUI elements from the worker thread. This leads to issues such that triggering the async operation multiple times (each time allowing completion) can lead to failure with messages like "recursive repaint detected" in PyQt5.

So my main questions, which I hope will serve also as documentation:

- How can one emulate the QThread style signal-slot communication from a worker thread?
- What is the difference between Event and Signal? Where should they be used?
- I've read atom.Event should be assigned to, but not called. What is the difference?
- I see that atom.Signal can be called, but it can also be emitted. What is the difference?

To provide a more concrete version of the issue, I provide some (incomplete) code that is hopefully readable.

```python
import threading
import atom.api as atom

class MyModel(atom.Atom):
     value = atom.Int()
     interval = atom.Float(0.25) # seconds
     percent = atom.Signal() # or atom.Float() or atom.Event() ?

    def trigger_async(self, target):
          op = TriggeredOperation(model=self, target=target)
          thread = threading.Thread(target=op.start)
          thread.start()  # changes to self.percent from worker thread will update GUI elements


class TriggeredOperation(atom.Atom):
     model = atom.Instance(MyModel)
     target = atom.Int()

    def start_async_operation(self):
        start = self.model.value
        self.trigger_async_op()
        done = False
        while not done:
            time.sleep(self.model.interval)
            current = self.get_op_status()
            percent = (self.target-current)/(self.target-start) * 100

            # How to signal this percent back to the GUI thread which triggered this operation?
            self.model.percent.emit(percent)   # for atom.Signal
            # self.model.percent = percent     # for atom.Float

            if percent > 100:
                done = True

# somewhere in gui land
enamldef SomeWidget(Container):
    attr model: MyModel

    SpinBox: spin:
        pass
    PushButton:
        text = "trigger"
        clicked:: model.trigger_async(spin.value)
    ProgressBar:
        value << int(model.percent)

```

Your help & comments will be much appreciated.

**Comment by achennu** [comment]
Strangely, my earlier searches did not show it up. But going back to google brought up this solution:
https://gist.github.com/sccolbert/8569752

Sorry for the noise. Once I get that working, I'll try to contribute an example for the docs. Please close if there is not more to add at this point.

**Comment by MatthieuDartiailh** [comment]
An example would indeed be great. You can look at `application.py` for more details about using deferred_call or other similar mechanisms.
