### ISSUE TITLE
Python 2 support plans

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#315]
With Python 2 end of life approaching and most projects having defined a clear politics (https://docs.scipy.org/doc/numpy-1.14.0/neps/dropping-python2.7-proposal.html), it would make sense to do the same (for all projects under the nucleic organization).

Given the limited amount of time, maintainers have for those projects I propose to follow numpy schedule and stop adding new features to Python 2 in 2019. The next release including Python 3.7 support will (save if a major bug is reported) probably be the last one supporting Python 2. Should the need arise, bugfix could be back-ported. The first release without Python 2 support will bump the minor version number in all projects.

Opinions ?

The most likely to appear new features will be the typed dict and set in atom along with the transition to cppy for the C-API layer in all projects.

**Comment by deepankarsharma** [comment]
Is Python 2 support something that is holding things back or something that is a huge support burden?

**Comment by tstordyallison** [comment]
this is now done - I guess this issue can be closed?

**Comment by jason-s** [comment]
I hadn't even realized there were still Python 2 updates going on.

My only request is that the old version of Python 2 enaml is still available, as is, on conda. I have a Python 2 app that I keep trying to port to Python 3, and it never quite makes it, but it works fine in Python 2 and I need this to keep running.

**Comment by tstordyallison** [comment]
Support was dropped quite a while ago I'm afraid!

But it is still all on conda.

I was pointing out that this issue can now be closed.

**Comment by MatthieuDartiailh** [comment]
The existing release either on conda or pipy won't go away but Pyrhon 2 support has indeed been dropped several years ago.
