### ISSUE TITLE
Is possible to create tabbed DockItem on demand?

### ISSUE THREAD

**Issue by zenchanhk** [nucleic/enaml#319]
Hi,

I'm wondering if it's possible to create tabbed `DockItem`s on demand? I have a list of objects containing name and title for `DockItem`s, and want to put `DockItem`s in tabbed form in `DockArea`. I've tried `Include` in `DockArea`, and `InserItem` in `initialized` event, but neither of them work. Could anyone help me with this?

**Comment by frmdstryr** [comment]
See https://enaml.readthedocs.io/en/latest/api_ref/layout/dock_layout.html?highlight=InsertTab#enaml.layout.dock_layout.InsertTab

**Comment by zenchanhk** [comment]
Thank you. I will try it later.
