### ISSUE TITLE
is it possible  to  have screen  manager  like kivy?

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [nucleic/enaml#320]
I  was wondering  if it possible  to change from one screen  to another  like kivy screen manager

**Comment by MatthieuDartiailh** [comment]
Do you mean on mobile or on the desktop ? Since you mention Kivy I imagine you are targeting mobile platforms, in which case you should open an issue in enaml-native bug tracker, since the only official backend of enaml is Qt.

**Comment by MatthieuDartiailh** [comment]
Please add a reference to the issue in enaml-native and close this one when you will have opened one in enaml-native.

**Comment by Mohamed-Kaizen** [comment]
https://github.com/codelv/enaml-native/issues/71
