### ISSUE TITLE
Bad links on PyPI page

### ISSUE THREAD

**Issue by rogererens** [nucleic/enaml#322]
On https://pypi.org/project/enaml/, there are 5 links to http://nucleic.github.io that are 404s.

**Comment by MatthieuDartiailh** [comment]
Thanks for pointing this out. I will fix it for the next release (which should be out next week hopefully).

**Comment by MatthieuDartiailh** [comment]
Actually this has been fixed in a previous rework of the resume. PyPI will be fixed in the next release.
