### ISSUE TITLE
Notebook example broken

### ISSUE THREAD

**Issue by cryzed** [nucleic/enaml#327]
Hello, the [notebook example](https://enaml.readthedocs.io/en/latest/examples/ex_notebook.html) is broken, clicking on "Open Bar Page" or "Open Baz Page" does nothing. Also setting the `selected_tab` is impossible without accessing the underlying framework's object name for the proxied widget -- it would be much more sensible if `selected_tab` was named `selected_page` and was able to be set to a page.

EDIT: I should probably mention that this happens using PyQt5.

**Comment by MatthieuDartiailh** [comment]
Thanks for the report I will try investigate later this week.

**Comment by MatthieuDartiailh** [comment]
I believe that the example is simply not clear enough since actually everything works. Please have a look at #329.
