### ISSUE TITLE
Question: using ENAML for web apps?

### ISSUE THREAD

**Issue by worldmind** [nucleic/enaml#332]
Hi, thank for very interesting project - for first look it a right way for creating GUI.
It is crossplatform, but what about web? Maybe it is possible to use ENAML with such projects like [pureqml](https://github.com/pureqml/qmlcore), [qmlweb](https://github.com/qmlweb/qmlweb) and [etc](https://github.com/qmlweb/qmlweb#related-efforts) or another way?

**Comment by MatthieuDartiailh** [comment]
Hi, 
Even if enaml main backend is qt it does not use qml at all, so I don't think it would make sense to use the other project you mentioned. 
For web development you can give a look at https://github.com/codelv/enaml-web.

**Comment by worldmind** [comment]
Thanks for answer and link!
