### ISSUE TITLE
Adding VTKCanvas to Container affects other items in container

### ISSUE THREAD

**Issue by gpettit** [nucleic/enaml#334]
When adding a VTKCanvas item to a container, it appears to affect the size and layout of other items in the container.  Should this be possible?  

```python
from enaml.widgets.api import ( 
            Window, Container, VTKCanvas, Label
        )

enamldef Main(Window):
    title = 'VTKCanvas Test'
    Container:
        Label:
            text = 'this is a test...'
        Label:
            text = 'this is another test...'
        # VTKCanvas:
            # pass
```
Without VTKCanvas:
<img width="312" alt="without_vtkcanvas" src="https://user-images.githubusercontent.com/25906182/49604718-a710be80-f95c-11e8-9874-13cbfd66f030.png">
With VTKCanvas
<img width="532" alt="with_vtkcanvas" src="https://user-images.githubusercontent.com/25906182/49604740-b0019000-f95c-11e8-9327-a675bf516be5.png">

platform: macos
python: homebrew version 2.7

```bash
Name: enaml
Version: 0.10.2
Summary: Declarative DSL for building rich user interfaces in Python
Home-page: https://github.com/nucleic/enaml
Author: The Nucleic Development Team
Author-email: sccolbert@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages
Requires: setuptools, kiwisolver, qtpy, ply, atom, future
Required-by:

Name: vtk
Version: 8.1.2
Summary: VTK is an open-source toolkit for 3D computer graphics, image processing, and visualization
Home-page: https://vtk.org/
Author: VTK Community
Author-email: vtk-developers@vtk.org
License: BSD
Location: /usr/local/lib/python2.7/site-packages
Requires:
Required-by:
```

note: I did have to add a symbolic link in the vtk python package that points to qt from qt5, but I noticed this was fixed in a later commit.

**Comment by MatthieuDartiailh** [comment]
What version of pyqt are you using ? Do you have a RetinaDisplay ? 

I would suspect some weird interaction between vtk and pyqt about what is the screen resolution of a Mac. I will try to look into it but it may take me some time. Do not hesitate to ping me.

**Comment by gpettit** [comment]
The pyqt version is 5.10.1 and I do have a retina display.  Looks like you are correct, I just plugged my laptop into a standard resolution external monitor and the problem disappeared.  I will investigate further.

Thanks for the quick response!

**Comment by MatthieuDartiailh** [comment]
Interesting. Hopefully they will fix the regression.
