### ISSUE TITLE
Crash with the next message

### ISSUE THREAD

**Issue by jedi2light** [nucleic/enaml#336]
Arch Linux
Plasma 5.14.5-1
QT 5.12.0-2
Python 3.7.2
Enaml, atom installed from pip, both have version 0.4.1
Script that I tried to run is example view.enaml from documentation

```
corrupted double-linked list
QSettings::value: Empty key passed
QSettings::value: Empty key passed
```

**Comment by sccolbert** [comment]
What exactly did you have in mind by posting that? There's certainly not
enough information for us to reproduce it, and there is zero evidence that
enaml is the cause.

This is the definition of a non-actionable bug report.

**Comment by MatthieuDartiailh** [comment]
The enaml version you report does not make sense. What is the output `pip list` ? Also note that the atom version on pip does not yet support Python 3.7 so you can try to run on 3.6.

**Comment by jedi2light** [comment]
I tested enaml on another Arch Linux desktop with XFCE DE with exactly same versions of components and enaml example worked fine, strange...

**Comment by jedi2light** [comment]
> `pip list`
```
atom              0.4.1             
enaml             0.10.2
```

Oh, sorry, I have mentioned wrong version of enaml package above

**Comment by MatthieuDartiailh** [comment]
To me this sounds like a Qt bug on plasma. Not sure enamel can do anything about it.

**Comment by MatthieuDartiailh** [comment]
I will close since this is unlikely to be related to enaml but looks more like a Qt/Plasma bug. Feel free to re-open with additional information is relevant.
