### ISSUE TITLE
Is there any example of Icon or IconImage widgets usage as Action.icon attribute

### ISSUE THREAD

**Issue by jedi2light** [nucleic/enaml#337]
I found doc for these both classes in API reference, but I wonder how I can use icons for actions in menu for example.

**Comment by frmdstryr** [comment]
Yes, please search before creating issues: https://github.com/nucleic/enaml/search?q=Action.icon&unscoped_q=Action.icon

**Comment by jedi2light** [comment]
Oh, thank you!
