### ISSUE TITLE
Issues with enaml application on X11 using certain window managers

### ISSUE THREAD

**Issue by lrozema** [nucleic/enaml#339]
### One way of reproducing:
Run the hello world enaml application on the IceWM window manager. It will pop up an empty window. Only after resizing the window will 'Hello world' magically appear.

### Background:
We have developed an enaml application that we normally use on a standard Ubuntu installation. For automated testing of the application we use pyautogui in a vnc X11 server using openbox as window manager and noticed that at certain points the main window would not come back on screen. Suspecting an enaml bug we decided to switch window managers during automated testing. We couldn't get gnome to work as it had certain X server requirements that the vnc server didn't seem to offer. Fluxbox didn't solve the issue. IceWM showed the issue the soonest.

#### Before resizing:
![screenshot 2019-02-03 at 15 50 58](https://user-images.githubusercontent.com/4730397/52178198-939e9a00-27cb-11e9-8686-3f7f4b97a432.png)

#### After resizing:
![screenshot 2019-02-03 at 15 51 09](https://user-images.githubusercontent.com/4730397/52178197-91d4d680-27cb-11e9-8572-e0764a83cc25.png)

**Comment by sccolbert** [comment]
This is more than likely an issue with Qt, not Enaml.

Simple test: create a QWidget with a child QLabel and see if it exhibits
the same behavior.

**Comment by lrozema** [comment]
Indeed a Qt issue. Thanks.
