### ISSUE TITLE
Use super to access overridden expressions

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#340]
Would it be possible (and make sense) to allow the use of  `super.attr` with read operators (`=` and `<<`)?  Or is there some way to do this?

I mainly would like this for enaml-web where you're constantly modifying the default css classes.  I currently need to define two fields `default_cls` and `cls` then use `cls << default_cls + 'my-new-classes'` so I don't have to repeat all the default css classes.

A stupid example but:

```python

enamldef Button(A):
   cls = 'btn' # Some real use cases have many classes

enamldef Page(Html):
   # ...
   Button:   
       cls = super.cls + ' btn-blue'

```

**Comment by sccolbert** [comment]
I see how that could be useful, but not sure we want to tackle implementing
it. You might be able to do what you want with `func` definitions.

**Comment by frmdstryr** [comment]
I got it to work :+1:  , see https://github.com/nucleic/enaml/compare/master...frmdstryr:super-attr-test

The proxy is obviously a hack but could something similar be done in the dynamic scope?

```python
from enaml.widgets.api import Window, Container, Label

enamldef Link(Label):
    attr cls = "btn"
    text << str(cls)

enamldef Main(Window):
    Container:
        Link:
            cls = super.cls + ' btn-blue'
```

**Comment by sccolbert** [comment]
I'd be interested to see the memory impact of this change on a large
application.

**Comment by frmdstryr** [comment]
The largest application I have is Inkcut, it doesn't seem to make much of a difference.

```python
Before

The process inkcut (with pid 12322) is using approximately 125.7 MB of memory.
It is using 123.8 MB privately, and a further 14.1 MB that is, or could be, shared with other programs.
Dividing up the shared memory between all the processes sharing that memory we get a reduced shared memory usage of 1914.0 KB. 
Adding that to the private usage, we get the above mentioned total memory footprint of 125.7 MB.


After
The process inkcut (with pid 12418) is using approximately 125.9 MB of memory.
It is using 124.0 MB privately, and a further 14.2 MB that is, or could be, shared with other programs.
Dividing up the shared memory between all the processes sharing that memory we get a reduced shared memory usage of 1907.0 KB. 
Adding that to the private usage, we get the above mentioned total memory footprint of 125.9 MB.

```

I did it twice and it's repeatable. 


I'm guessing because it only works for one level. Any nesting is giving recursion errors, ex this does not work:

```python
enamldef A(Label):
    text = "a"

enamldef B(A):
    text = "b" + super.text

enamldef Main(Window):
    Container:
        B:
            text = super.text

```

```python-traceback
  File "tests/example.enaml", line 7 in <module>
  File "/home/jrm/Workspace/enaml/enaml/core/standard_handlers.py", line 74 in __call__
  File "/home/jrm/Workspace/enaml/enaml/core/expression_engine.py", line 189 in read
  File "/home/jrm/Workspace/enaml/enaml/core/standard_handlers.py", line 24 in __getattr__
  File "tests/example.enaml", line 7 in <module>
  File "/home/jrm/Workspace/enaml/enaml/core/standard_handlers.py", line 74 in __call__
  File "/home/jrm/Workspace/enaml/enaml/core/expression_engine.py", line 189 in read
  File "/home/jrm/Workspace/enaml/enaml/core/standard_handlers.py", line 24 in __getattr__
  File "tests/example.enaml", line 7 in <module>
```


So this is not really a good solution... somehow a reference to only the enamldef declaration node needs to be assigned as 'super' but I can't figure out how or where that is :).

**Comment by frmdstryr** [comment]
Got it to work with multiple super classes in https://github.com/nucleic/enaml/compare/master...frmdstryr:super-attr-bases

```python
from enaml.widgets.api import Window, Container, Label

enamldef A(Label):
    text = "a"

enamldef B(A):
    text = super.text + "b"

enamldef C(B):
    text = super.text + "c"

enamldef Main(Window):
    Container:
        C:
            text = super.text + 'd'

```

Displays `abcd`. 

But it needs more testing, also `super` may be a bit of a misnomer because it can only access overridden expressions. 

Any thoughts?

**Comment by MatthieuDartiailh** [comment]
I was planning to comment but I never found the time. I am not extremely enthusiastic about this because I suspect it could easily be misused (access something that is not static). I would feel more comfortable with a function taking the parent and the field name.

**Comment by frmdstryr** [comment]
Would saving a reference to the compiler node be acceptable? 
See:  https://github.com/nucleic/enaml/compare/master...frmdstryr:declarative-node-ref?expand=1

Or is there currently a way for a declarative instance to know what it's "super node" (not the parent) is?  

Saving a reference to the compiler node allows walking up the super_node's to find and run it's handlers.

**Comment by frmdstryr** [comment]
Bump. Any comments?

**Comment by sccolbert** [comment]
I'm not super enthused with this idea, particularly surrounding the complexity relating to ensuring all the tracing works properly. I'm not convinced that this is a better solution to calling into regular Python or a normal method.
