### ISSUE TITLE
How to integrate with QButtonGroup?

### ISSUE THREAD

**Issue by djmattyg007** [nucleic/enaml#342]
I have a need to display several radio buttons within their own containers, while still ensuring they are part of the same group for exclusivity purposes. My understanding is that this is facilitated by the QButtonGroup class. However, there doesn't appear to be a wrapper for this in the enaml framework. Am I missing something? How could I go about implementing support myself?

**Comment by MatthieuDartiailh** [comment]
Hi,
Could you describe in more details your use case ? Why do you need the buttons to be within different containers ? I am asking to see if there could not be a different solution to your problem.

**Comment by sccolbert** [comment]
RadioButtons when share the same parent Container are automatically exclusive. You don't need  to anything extra.

**Comment by djmattyg007** [comment]
This is a cut-down example from my code:

```
GroupBox: ctn_choices:
    title = "My group box"
    ScrollArea:
        constraints = [width >= 220, height <= 160]
        Container:
            Looper:
                iterable << [1, 2, 3, 4, 5]
                Container:
                    constraints = [hbox(radio, spacer, button)]
                    RadioButton: radio:
                        text << "Choice {0}".format(loop_item)
                    PushButton: button:
                        text = "Play"
```

I need every radio button inside `ctn_choices` to be in the same button group.

**Comment by sccolbert** [comment]
Get rid of the Container within the Looper and use the outer Container to
apply the contraints to the items created by the Looper.

Give the looper an id, and you can reference the widgets it creates via
`looper_id.items`:
https://github.com/nucleic/enaml/blob/master/enaml/core/looper.py#L47

**Comment by djmattyg007** [comment]
Thanks, I was able to get it working by using the factory layout helper. However, I'm not sure if this would be feasible for more complex layouts. Surely it would still be worth having some way of assigning buttons to groups manually, so that the developer has full control?

**Comment by sccolbert** [comment]
Back when I wrote this, we were supporting the Wx backend as well, which doesn't have the concept of a button group. I determined it not to be worth the effort to try to force that concept into the system.

This reminds me (IIRC). There is a little known feature of Qt where any button with the same `name` (in an entire app) will automatically act like it's in a button group. So you may be able to achieve what you want by assigning your buttons the same `.name` to some unique value. This in untested, but I think it will work.

**Comment by MatthieuDartiailh** [comment]
Given Enaml layout flexibility (which deserves a better documentation but that is on my list), the lack of concrete use case for an alternative and the global lack of time of the developers to implement such a feature, I will close the issue since the immediate issue has been solved. 
@djmattyg007 if you have the time and the interest to develop a way to group buttons, I will be happy to review a PR and discuss the implementation.
