### ISSUE TITLE
Instant/customizable auto_sync trigger timeout?

### ISSUE THREAD

**Issue by nhanb** [nucleic/enaml#352]
I'm trying to implement a text input widget that becomes green whenever its current text differs from the default text. Here's my attempt:

```
from enaml.widgets.api import Window, Container, Field
from enaml.styling import StyleSheet, Style, Setter

enamldef Main(Window):
    StyleSheet:
        Style:
            element = 'Field'
            style_class = 'dirty'
            Setter:
                field = 'background-color'
                value = 'lightgreen'
    Container:
        Field:
            style_class << '' if self.text == 'default' else 'dirty'
            text = 'default'
            submit_triggers = ['auto_sync']
```

It works but the color only gets updated 300ms after user stops typing, which IMO doesn't feel snappy. Turns out this timeout is hardcoded in the [current auto_sync implementation](https://github.com/nucleic/enaml/blob/f65af3b70a2b91027ec668fe8decc766ca8d030f/enaml/qt/qt_field.py#L205-L210). How difficult would it be to make this timeout configurable?

Or is there a different way to implement instant as-you-type style updates? I see keypress events [haven't been implemented](https://github.com/nucleic/enaml/issues/256) so that sounds like a dead end.

**Comment by MatthieuDartiailh** [comment]
Making this timeout configurable should be possible and not too hard. @sccolbert are you fine with adding that option ? 
I will try to put together a PR for this in the coming days.

**Comment by sccolbert** [comment]
I approve of the PR to make the timeout configurable, however why not use the `placeholder` attribute for this use case?

**Comment by MatthieuDartiailh** [comment]
The placeholder attribute does not allow to modify the style of the widget even though I agree it gives the same kind of visual indication. Not sure why the color change is important to @nhanb .

**Comment by nhanb** [comment]
Ah my use case is quite different: I'm building a GUI control panel for a live scoreboard display. The goal is something like this:

![diff-2019-07-11_21 49 56](https://user-images.githubusercontent.com/1446315/61061248-1506f200-a426-11e9-8a83-d058f66e512a.gif)

The green background indicates that a field has changes that have not been applied to the actual scoreboard. Placeholder doesn't quite fit in here.

It was implemented in tk just fine but the way tkinter does layout is just too cumbersome so I'm trying to port it to enaml.

By the way, I didn't expect to get such quick replies _and a PR already_. You guys rock! Is there a planned release any time soon or should I expect to build from master myself once this gets merged?

**Comment by MatthieuDartiailh** [comment]
Now that #353 was merged I will close this. I am not planning a new release soon (this is the only recent feature added, and some of the background work I started is not done yet). If you really need a release I can make one however.

Also note that you caught at a good time with a non-controversial change. I cannot promise it will always be that easy.

**Comment by nhanb** [comment]
Totally reasonable. I don't think I'll need any more extra features, so could you please make a release this one time @MatthieuDartiailh?
