### ISSUE TITLE
Appveyor no longer tests on Windows.

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#354]
Back in #272, I complained that tests for Enaml were not being run on the Windows platform.

I argue that if you don't run tests on a platform, you can't honestly say you support it. Problems creep in that are not detected. In particular, the build and installation instructions for Windows became confusing.

To remedy this, I added Windows support to the CI testing. Travis doesn't support this, so I had to introduce AppVeyor.

However, a [recent commit](https://github.com/nucleic/enaml/commit/ae11e34ba3176682f91249ee488c4a6ee584e9b7) modified the AppVeyor yaml file to only run on Linux.

This is now:

1. duplicating the work already done in Travis
2. removing any tests of the code on windows, hiding any platform-specific issues that might be introduced.

**Comment by MatthieuDartiailh** [comment]
I am not sure I follow you Appveyor is running Windows as can be seen from the log of the last build https://ci.appveyor.com/project/nucleic/enaml/build/job/g21netlhvcusd78p. Also the commit you reference simply modify the python version used and set the system to add coverage report, it does not change anything os related.

**Comment by Julian-O** [comment]
OMG! I have totally misread the change. So sorry for wasting your time.

**Comment by MatthieuDartiailh** [comment]
No big deal. I hope to address your other issue later today or tomorrow at the latest.
