### ISSUE TITLE
Installation document doesn't mention Python 3.7

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#356]
The [Installation guide](https://enaml.readthedocs.io/en/latest/get_started/installation.html) says:

> Enaml is a Python framework and requires a supported Python runtime. Enaml currently supports Python 2.7, Python 3.4, Python 3.5, and Python 3.6.

It should be updated to mention Python 3.7.

**Comment by MatthieuDartiailh** [comment]
True. I will do a minor release soon and will fix it.
