### ISSUE TITLE
Looper `loop_index` becomes invalid when items are reused

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#357]
This has really confused me for a long time...

```
import random
from enaml.core.api import Looper
from enaml.widgets.api import Window, Container, Label, PushButton


enamldef Main(Window): window:
    attr data: list = ['a', 'b', 'c']
    Container:
        PushButton:
            text = 'Shuffle'
            clicked ::
                d = window.data[:]
                random.shuffle(d)
                window.data = d
        Looper:
            iterable << window.data
            Label:
                text << '{} {} {}'.format(loop_index, loop_item, data.index(loop_item))


```

Initially it shows

```
0 a 0
1 b 1
2 c 2
```

After shuffling it shows

```
2 c 0
0 a 1
1 b 2
```

I would expect `loop_index` to always match the index of the item within the iterable but that is not the case when items are reordered.

**Comment by sccolbert** [comment]
Looper tries to be smart and caches the rendered widgets inside the loop and simply moves them to the new location when the looper re-renders. What this means is that you shouldn't modify the iterable in-place. Create a copy of it, and you should be good to go.

**Comment by frmdstryr** [comment]
The problem actually came up in code that was using a new list each time but a few items in the list were in a different position (changing options for a select field with enaml-web).  

The only easy way to do it is to wrap the iterable with `enumerate` but that defeats the point of caching because even if the item moves the whole widget needs rerendered as the (index, item) tuple changes.  

The PR I pushed tries to retain the intent of caching when items are moved but still need to update some members that depend on the index.

**Comment by MatthieuDartiailh** [comment]
@frmdstryr do you consider this is not worth fixing ? I was in vacation the last two weeks and missed this.

**Comment by frmdstryr** [comment]
Not sure, I haven't run into issues with it often. It depends on how people use loop_index.  

If not fixed I think it should at least be documented. Feel free to reopen.

**Comment by frmdstryr** [comment]
#358
