### ISSUE TITLE
Attribute error when Image is None

### ISSUE THREAD

**Issue by Julian-O** [nucleic/enaml#360]
Background:

I had an old Enaml-based tool that was working fine. I rebuilt my Windows OS and almost certainly changed versions of various dependencies (perhaps including the Qt implementation) and it stopped working.

The tool displays an Image from a file, once the filename is selected. When it first starts, no file is selected, so the ImageView's image is initialised with None.

Under the old system, this was fine - no image would appear.
Under the new system, during the initialisation, `ImageView.layout_constraints()` calls `self.proxy.get_aspect_ratio()` which calls `QtImageView.get_aspect_ratio()` which calls `pixmap.size()`. However, `pixmap` is None.

> AttributeError: 'NoneType' object has no attribute 'size'

Why is `pixmap` None? Because when `QTImageView.set_image()` was called, the image parameter was None.

I don't know exactly what changed. I now am installing from pip, using `enaml` (0.10.3) and `pyqt5` (5.13.0)

The system should either accept None to `ImageView` objects without error (preferred), or reject it explicitly with a relevant exception or assertion, rather than leave it till later to die mysteriously, and leave the user to debug the cause.

(My workaround is to put a placeholder image in, instead of None.)

**Comment by MatthieuDartiailh** [comment]
Thanks for reporting. I will have a pull request ready today. I am planning a release by the end of the month (pending some PRs I need @sccolbert opinion on) and I will include this fix in it.

**Comment by MatthieuDartiailh** [comment]
See #361
