### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#362]
This is a meta to track the changes associated with Python 3.8:

Required changes (meaning enaml won't run without them):
- bytecode changes:
  - MAP_ADD: the expected order on the TOS changed 
  - BREAK_LOOP, CONTINUE_LOOP, SETUP_LOOP, SETUP_EXCEPT have been removed and as a consequence the code_generator `for_loop` and `try_squash_raise` need to be updated.
  - ROT_FOUR, BEGIN_FINALLY, CALL_FINALLY, POP_FINALLY have been added which may impact `try_squash_raise`.
  - END_FINALLY and WITH_CLEANUP_START changed of behavior
  - CodeType signature changed

Those require to update wbyteplay and in particular the stack trace calculation and since we will be dropping Python 2 it may be the proper time to switch to https://github.com/vstinner/bytecode which a more modern interface to the Python bytecode.

Other changes (required for feature parity with normal Python):
- support for assignment expression (may cause grammar issue, and is tightly related to https://github.com/nucleic/enaml/pull/348)
- positional only argument (change to the parser but should not be a big problem, except it may mean the AST for function may have change which would imply more pervasive changes)
- f-strings now have a new formatting mode marked by '='
- continue is now allowed in finally clause (not sure we were actively preventing it on the parser side)
- the rules for unpacking in yield and return have changed.

**Comment by Techjar** [comment]
That has become a significant problem as Python 3.8 is now in the main Arch Linux repository.

**Comment by sccolbert** [comment]
@Techjar you're welcome to fix it, and make a PR.

**Comment by MatthieuDartiailh** [comment]
Current master should run on Python 3.8 however the following points have not been addressed yet:
- support for assignment expression
- new rules for unpacking in yield and return

**Comment by ShyPixie** [comment]
I've built cppy and enaml from git but I keep receiving a NameError about BREAK_LOOP not defined

**Comment by MatthieuDartiailh** [comment]
Could you share your test file I will try to investigate ?

**Comment by bburan** [comment]
Ran into this. Pretty sure it's a bad build uploaded to anaconda (at least for Linux). Here's a minimal working example:

    conda create -n enaml-test enaml
    conda activate enaml-test
    python test.py

Where `test.py` is:

    import enaml
    with enaml.imports():
        pass

Giving the traceback:

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    with enaml.imports():
  File "/home/bburan/bin/miniconda3/envs/enaml-test/lib/python3.8/site-packages/enaml/__init__.p
y", line 61, in imports
    from enaml.core.import_hooks import imports
  File "/home/bburan/bin/miniconda3/envs/enaml-test/lib/python3.8/site-packages/enaml/core/impor
t_hooks.py", line 24, in <module>
    from .enaml_compiler import EnamlCompiler, COMPILER_VERSION
  File "/home/bburan/bin/miniconda3/envs/enaml-test/lib/python3.8/site-packages/enaml/core/enaml
_compiler.py", line 11, in <module>
    from . import compiler_common as cmn
  File "/home/bburan/bin/miniconda3/envs/enaml-test/lib/python3.8/site-packages/enaml/core/compi
ler_common.py", line 16, in <module>
    from . import byteplay as bp
  File "/home/bburan/bin/miniconda3/envs/enaml-test/lib/python3.8/site-packages/enaml/core/bytep
lay/__init__.py", line 11, in <module>
    from .wbyteplay import *
  File "/home/bburan/bin/miniconda3/envs/enaml-test/lib/python3.8/site-packages/enaml/core/bytep
lay/wbyteplay.py", line 92, in <module>
    BREAK_LOOP,
NameError: name 'BREAK_LOOP' is not defined
```

Pretty sure it's a bad build because when I install from source code, I don't get the error.

**Comment by bburan** [comment]
Hmm. I just noticed that @ShyPixie mentioned building from Git. Odd. So, it sounds like we might have two separate issues?

**Comment by MatthieuDartiailh** [comment]
For the time being there is no release with support for Python 3.8. Conda may have though everything was fine (I may even have merged a PR on conda-forge I don't remember).

**Comment by bburan** [comment]
Thanks for clarifying. 

For what it's worth conda came up with a "solution" for Enaml + Python 3.8 (which, of course, created a nonfunctional environment). Definitely a different issue from @ShyPixie who needs to provide a minimal working example to help resolve the issue reported.

**Comment by ShyPixie** [comment]
Sorry for later
I was in this situation:

```
Python 3.8.1 (default, Jan 25 2020, 17:01:17)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enaml
>>> enaml.__spec__
ModuleSpec(name='enaml', loader=<_frozen_importlib_external.SourceFileLoader object at 0xffffa9f07760>, origin='/usr/lib/python3.8/site-packages/enaml/__init__.py', submodule_search_locations=['/usr/lib/python3.8/site-packages/enaml'])
>>> with enaml.imports():
...     pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/enaml/__init__.py", line 61, in imports
    from enaml.core.import_hooks import imports
  File "/usr/lib/python3.8/site-packages/enaml/core/import_hooks.py", line 24, in <module>
    from .enaml_compiler import EnamlCompiler, COMPILER_VERSION
  File "/usr/lib/python3.8/site-packages/enaml/core/enaml_compiler.py", line 11, in <module>
    from . import compiler_common as cmn
  File "/usr/lib/python3.8/site-packages/enaml/core/compiler_common.py", line 16, in <module>
    from . import byteplay as bp
  File "/usr/lib/python3.8/site-packages/enaml/core/byteplay/__init__.py", line 11, in <module>
    from .wbyteplay import *
  File "/usr/lib/python3.8/site-packages/enaml/core/byteplay/wbyteplay.py", line 92, in <module>
    BREAK_LOOP,
NameError: name 'BREAK_LOOP' is not defined
>>> from enaml import version
>>> version.__version__
'0.10.4'
```
but after remove and reinstall:

```
Python 3.8.1 (default, Jan 25 2020, 17:01:17)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enaml
>>> enaml.__spec__
ModuleSpec(name='enaml', loader=<_frozen_importlib_external.SourceFileLoader object at 0xffff821592b0>, origin='/usr/lib/python3.8/site-packages/enaml-0.10.4-py3.8-linux-aarch64.egg/enaml/__init__.py', submodule_search_locations=['/usr/lib/python3.8/site-packages/enaml-0.10.4-py3.8-linux-aarch64.egg/enaml'])
>>> with enaml.imports():
...     pass
...
>>> from enaml import version
>>> version.__version__
'0.10.4'
>>> 
```

Apparently python was looking in the wrong path. Honestly it doesn't look like a bug, may have been caused by my previous installation of enaml via pip

Thanks

**Comment by MatthieuDartiailh** [comment]
Ok so everything seems fine and I really to find time to a push a release out...

**Comment by AlexandrParkhomenko** [comment]
**from enaml.core.import_hooks import imports**  ;-)

```
Python 3.8.2 (default, Feb 26 2020, 22:21:03) 
[GCC 9.2.1 20200130] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enaml
>>> from enaml.core.import_hooks import imports
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/enaml/core/import_hooks.py", line 24, in <module>
    from .enaml_compiler import EnamlCompiler, COMPILER_VERSION
  File "/usr/lib/python3.8/site-packages/enaml/core/enaml_compiler.py", line 11, in <module>
    from . import compiler_common as cmn
  File "/usr/lib/python3.8/site-packages/enaml/core/compiler_common.py", line 16, in <module>
    from . import byteplay as bp
  File "/usr/lib/python3.8/site-packages/enaml/core/byteplay/__init__.py", line 11, in <module>
    from .wbyteplay import *
  File "/usr/lib/python3.8/site-packages/enaml/core/byteplay/wbyteplay.py", line 92, in <module>
    BREAK_LOOP,
NameError: name 'BREAK_LOOP' is not defined

```

**Comment by AlexandrParkhomenko** [comment]
[inkcut](https://github.com/inkcut/inkcut) ist  kaputt (German: not work)

**Comment by MatthieuDartiailh** [comment]
How did you install enaml ? Currently only the master branch supports Python 3.8 and byteplay in not used anymore.

**Comment by AlexandrParkhomenko** [comment]
git clone ...
python setup.py build
python setup.py test

NameError: name 'BREAK_LOOP' is not defined

**Comment by MatthieuDartiailh** [comment]
The latest published release of enaml 0.11.0 includes Python 3.8. Can you please try to install from PyPI ?

**Comment by AlexandrParkhomenko** [comment]
pip install enaml
Requirement already satisfied: enaml in /usr/lib/python3.8/site-packages (0.10.4)
sudo -i pip uninstall enaml
OK !

**python setup.py test**
    ======================================================================
ERROR: qt_occ_viewer (unittest.loader._FailedTest)
    ----------------------------------------------------------------------
ImportError: Failed to import test module: qt_occ_viewer
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "./python-enamlx-git/src/enamlx/enamlx/qt/qt_occ_viewer.py", line 16, in <module>
    from OCC.Display import OCCViewer
ModuleNotFoundError: No module named 'OCC'

pip search occ
occ (0.0.2.dev20190912195130)  - Octavia Chicken Checker looks for abandoned Octavia load balancer artifacts, amphoras, and so forth. Optionally it will clean them up as well.
NOT OK

https://aur.archlinux.org/packages/python-occ/
OK

inkcut
Traceback (most recent call last):
  File "/usr/bin/inkcut", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/inkcut/app.py", line 97, in main
    from inkcut.core.workbench import InkcutWorkbench
  File "/usr/lib/python3.8/site-packages/inkcut/core/workbench.py", line 16, in <module>
    enamlx.install()
  File "/usr/lib/python3.8/site-packages/enamlx/__init__.py", line 8, in install
    from enamlx.qt import qt_factories
  File "/usr/lib/python3.8/site-packages/enamlx/qt/qt_factories.py", line 8, in <module>
    from enaml.qt import qt_factories
ImportError: cannot import name 'qt_factories' from 'enaml.qt' (unknown location)

**Comment by MatthieuDartiailh** [comment]
Looking at what you did it seems that enaml is not installed anymore on your system since you uninstalled instead of upgrading to 0.11.0. Try to install 0.11.0 and test again. Also please report any issue you encounter with enamlx to enamlx repo rather than here.

**Comment by AlexandrParkhomenko** [comment]
`pip install enaml`

```
error:
File "/usr/lib/python3.8/site-packages/jupyter_client/client.py"
TypeError: ChannelABC() takes no arguments

fix:
pip install ipykernel  --upgrade
```

Thank you for your patience. There are no problems now.
