### ISSUE TITLE
cant set wrap length in multiline field

### ISSUE THREAD

**Issue by K3nn3th2** [nucleic/enaml#368]
I cannot find any solution to changing the wrap of a multiline field.
setting width in the constraints only cuts off part of the view.

any ideas on this?

**Comment by K3nn3th2** [comment]
nice too see i can answer my own question again ;)

setting 'resist-width' and 'resist-height' to weak (and setting the width) did the trick!

**Comment by MatthieuDartiailh** [comment]
Happy you fixed your issue !
