### ISSUE TITLE
Some images not displayed

### ISSUE THREAD

**Issue by K3nn3th2** [nucleic/enaml#383]
hey there,

as stated, some images from the net are not displayed for some reason.
i have added a small code example to demonstrate.
maybe somebody can clarify what the problem is.

```
import enaml
from enaml.image import Image
from enaml.layout.api import vertical, horizontal, align, spacer, vbox
from enaml.widgets.api import (
        Window, Label, Form, Container, PushButton, ImageView
        )
import threading, requests

image_riddimsworld = 'https://riddimsworld.com/wp-content/uploads/2015/12/20151215022457-150x150.jpg'
image_riddimsworld2 = 'https://riddimsworld.com/wp-content/uploads/money-jet-riddim-420x420.jpg'

enamldef ImageDownloader(Form): imgView:
    constraints = [
            vbox(txt,btn,)
            ]
    func dlThread():
        threading.Thread(target=loadImage).start()

    func loadImage():
        data = requests.get(image_riddimsworld)
        enaml.application.deferred_call(set_img_data, data.content)

    func loadImage2():
        data = requests.get(image_riddimsworld2)
        enaml.application.deferred_call(set_img_data, data.content)

    func set_img_data(data):
        img.image = Image(data=data)

    ImageView: img:
        pass    
    Label: txt:
        text = 'Some Description'
    PushButton: btn:
        text = 'load img'
        clicked :: loadImage()
    PushButton: btn2:
        text = 'load img (working)'
        clicked :: loadImage2()
        
enamldef Main(Window): main:
    ImageDownloader:
        pass

```

edit: it seems to work on windows. on linux, only the second button works for me.
edit2: updated code to match sccolbert's suggestions

**Comment by MatthieuDartiailh** [comment]
That looks weird. I will test on mac and see if I can reproduce.

**Comment by sccolbert** [comment]
You can't update the UI from anything but the main thread. Use
`enaml.application.deferred_call(...)` from your loader thread to get back
onto the main thread. Once you are on the main thread, *then* you can set
the image data.

**Comment by K3nn3th2** [comment]
thanks for the explanation. i updated my code to use deferred_call but the stated problem still persists.

**Comment by MatthieuDartiailh** [comment]
The example you provided works flawlessly on MacOSX. Could you tell me what flavor of Linux you are running since it seems I will have to set up a VM to debug this ?

**Comment by K3nn3th2** [comment]
I am running an x64 Arch Linux with LTS Kernel 4.19
My Python version was 3.7.8.

I updated it to 3.8 to see if it was python version related and now i cant run enaml code anymore. i end up with this error:

```
File "/usr/lib/python3.8/site-packages/enaml/core/byteplay/wbyteplay.py", line 92, in <module>
    BREAK_LOOP,
NameError: name 'BREAK_LOOP' is not defined

```
do you have any ideas what i could have messed up? i tried un- and reinstalling enaml already.. 
Sorry for the additional error to the error issue..

**Comment by MatthieuDartiailh** [comment]
We do not support 3.8 yet and it will take some time to add support (there has been numerous changes to Python bytecode).
What desktop are you running on (xfce, gnome, ...) ?

**Comment by K3nn3th2** [comment]
thanks for clarifying.
i am running i3

**Comment by K3nn3th2** [comment]
i downgraded back to 3.7.5 (needed a special aur package because the official python3 package moved to 3.8) and now its working. both images can be loaded! 
very weird, but i guess we can close this now :)

**Comment by MatthieuDartiailh** [comment]
Hopefully it does not re-appear.
