### ISSUE TITLE
Live reloading on code change

### ISSUE THREAD

**Issue by Norbo11** [nucleic/enaml#390]
Would this be at all possible? Has it been thought about and discarded? Has anyone managed to hack it together?

Related to #226

**Comment by frmdstryr** [comment]
I attempted in https://github.com/frmdstryr/enaml-hotswap 

 It doesn't work well.

**Comment by Norbo11** [comment]
> I attempted in https://github.com/frmdstryr/enaml-hotswap
> 
> It doesn't work well.

How come? :/

**Comment by MatthieuDartiailh** [comment]
Live reloading is in general hard in Python since there is no really clean way to check what modules have imported the module being reloaded and may hence have reference to classes defined in it.

**Comment by MatthieuDartiailh** [comment]
Live reloading is in general hard in Python since there is no really clean way to check what modules have imported the module being reloaded and may hence have reference to classes defined in it.
