### ISSUE TITLE
Support generator expressions in decl func blocks

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#392]
Currently on `0.10.2` this gives a syntax error
```python
if any(s for s in some_list if s <= 10):
  # SyntaxError: generator expressions not allowed in a declarative function block
```

But wrapping it in a list works fine

```python
if any([s for s in some_list if s <= 10]):
   # Life is good
```

also commenting out https://github.com/nucleic/enaml/blob/master/enaml/core/parser/base_parser.py#L760 works fine.

Is this exclusion necessary?

**Comment by MatthieuDartiailh** [comment]
I need to spend more time looking at the details of it but I believe this limitation comes from the need to run the generator expression in the proper scope to get have the right locals. I did quite a bit of work to get this to work for all comprehensions but never looked at generator expressions. 

Could you test it ? On straightforward way is by using `test_inner_functions.py` and adapting it to generator expr.

**Comment by MatthieuDartiailh** [comment]
Also note that this limitation is not limited to declarative functions but also in event handling blocks.

**Comment by MatthieuDartiailh** [comment]
Just for reference the rest of the discussion can be found in #393
