### ISSUE TITLE
NoFocus PushButton

### ISSUE THREAD

**Issue by AndiEcker** [nucleic/enaml#401]
As a total enaml newbie I struggle in declaring widgets (e.g. pushbuttons) that cannot receive the focus.

Is there a simple way to do this in the enamldef declaration, something like:

```
enamldef NoFocusButton(PushButton):
    proxy.widget.focusPolicy = QtCore.Qt.NoFocus
```

**Comment by frmdstryr** [comment]
You can use the [activated](https://enaml.readthedocs.io/en/latest/api_ref/widgets/toolkit_object.html#enaml.widgets.toolkit_object.ToolkitObject.activated) event

eg

```python
enamldef NoFocusButton(PushButton):
    activated ::    
        self.proxy.widget.focusPolicy = QtCore.Qt.NoFocus
```

**Comment by sccolbert** [comment]
Adding a `focus_policy` attribute would be a good addition to the base
`Widget` class:
https://github.com/nucleic/enaml/blob/master/enaml/widgets/widget.py#L134

**Comment by AndiEcker** [comment]
thanks for your quick replies!!!

Unfortunately the workaround in changing the focusPolicy property of the qt
widget in the activated event did not work.

Will study further and try to implement a `focus_policy` attribute to the
widget class.


Am Di., 31. März 2020 um 19:15 Uhr schrieb S. Chris Colbert <
notifications@github.com>:

**Comment by AndiEcker** [comment]
Are you sure @sccolbert that you want to have a `focus_policy` attribute
because you already had implemented it into enaml V 0.96
<https://github.com/nucleic/enaml/blob/e85a55ec957c361cb5ff5a4f781031dee0653ed1/releasenotes.rst#096---05082014>
but one version later it got removed.

Maybe you want that enaml users use instead your FocusTraversal feature,
something like:

```
enamldef NoFocusButton(PushButton):
    features = Feature.FocusTraversal

    previous_focus_child => (enaml_widget):
        return the_next_widget_that_can_receive_focus

    next_focus_child => (enaml_widget):
        return the_previous_widget_that_can_receive_focus
```

But when I set the FocusTraversal feature then I get an error at line 176
in
qt_widget.py (```if not widget.focusPolicy & Qt.TabFocus```), because
the focusPolicy attribute is actually a callable. FYI: in a previous enaml
version
this `if` expression was ```widget.focusPolicy*()* & Qt.TabFocus```)


¿Do you remember which problems you had with your implementation or why the
`focus_policy` attribute got removed in V 0.97?

¿Do you want me to fix the FocusTraversal bug first before I go further
with a new implementation of `focus_policy`?

**Comment by sccolbert** [comment]
Hmm, good find! That was so long ago, I don't remember why I added it then promptly removed it. It may have interfered with the focus traversal stuff, as you've found.

You've also found a bug. It should be `widget.focusPolicy()`. Looks like I screwed that up during a cleanup pass.

**Comment by sccolbert** [comment]
Also, if you look at the focus traversal example, you can define the traversal logic in an ancestor component. Sometimes it makes more sense for the ancestor to coordinate focus traversal.

**Comment by AndiEcker** [comment]
Ok, then I will first fix the little bug regarding the `widget.focusPolicy`
callable and then try to use the FocusTraversal feature

Anyway, thanks a ton for your quick answer and this great enaml framework!

Am Mi., 1. Apr. 2020 um 15:06 Uhr schrieb S. Chris Colbert <
notifications@github.com>:

**Comment by AndiEcker** [comment]
The focus traversal example is no longer crashing after fixing the bug (in
QtWidget.tab_focus_request() PR #403).

But the focus traversal example is still not working as expected.

For to see what is going on I added the enaml FocusTracker and some print
statements to this example
<https://github.com/AndiEcker/enaml_playground/blob/master/focus_traversal.enaml>
.

This is the console output of the extended example after pressing only once
Shift+Tab directly after starting it (field 1 is always getting the focus
on startup) - the comments on the right within << and >> got added by me to
the console output:

```
focused widget None
               1                                         <<app startup is
putting initial focus onto the first field 1 with placeholder 1>>
                                                          <<Shift+Tab
pressed>>
prev child 7                                        <<enaml func
previous_focus_child() gets called return correctly the field 5 with
placeholder 7 == the last widget in the focus traversal chain>>
focused widget 1                               <<FocusTracker output:
switch focus from field 1/1 to field 5 with placeholder 7>>
               7
prev child 6                                        <<here it starts
getting wrong: field 5/7 should actually keep the focus but somehow
previous_focus_child() gets called again>>
focused widget 7
               6
prev child 5
focused widget 6
               5
focused widget 5
               1                                         <<resulting that
the focus stays at field 1/1>>
```

Also after pressing the Tab key after the startup of the example the focus
gets first set correctly but then additional calls to the func
next_focus_child() is messing it up:

```
focused widget None
               1
                                                          <<Tab pressed>>
next child 2                                        <<func
next_focus_child() gets called return correctly the field 4 with
placeholder 2>>
focused widget 1
               2
next child 3                                        <<here it starts
getting wrong: field 4/2 should actually keep the focus but somehow
next_focus_child() gets called again>>
focused widget 2
               3
next child 4
focused widget 3
               4
focused widget 4
               6                                          <<resulting that
the focus changed to field 7 with placeholder 6>>
```

Another strange thing is that in both directions (Tab and Shift+Tab) there
are not all fields included: there are only 5 different widgets (of the 7
widgets) included in each focus chain.

All this does not make any sense to me. Unfortunately I cannot debug all in
Python because QtWidget.setFocus() is C++ code.

I will investigate further and hope I can find the problem. Maybe somebody
else can shed some light on this focus chain mess.

Am Mi., 1. Apr. 2020 um 15:30 Uhr schrieb Andreas Ecker <aecker2@gmail.com>:

**Comment by AndiEcker** [comment]
update: if you change the value of the last return statement in
QtWidget.tab_focus_request() from False to True the focus traversal example
is working correctly.

Looks like I I found another bug in the same method - I will provide a pull
request...



Am So., 5. Apr. 2020 um 18:23 Uhr schrieb Andreas Ecker <aecker2@gmail.com>:

**Comment by AndiEcker** [comment]
made pull request #404 for to fix the problem of the focus traversal
example.

instead of returning True I put `widget.hasFocus()` as return value to
ensure that new focus widget has not rejected the focus.

Will keep this issue still open and keeping you informed until I found a
definitive solution for the initial no-focus problem/fix/implementation.

Am So., 5. Apr. 2020 um 19:27 Uhr schrieb Andreas Ecker <aecker2@gmail.com>:

**Comment by AndiEcker** [comment]
Confirming that with the new enaml version 0.11.0 one can prevent in most cases that certain widgets are receiving the focus. For that the [focusTraversal feature has to be set](https://github.com/nucleic/enaml/blob/91e354efb2cf24691da63165fd331bb0bb653c18/examples/widgets/focus_traversal.enaml#L34), best in the root/main window of your application. Additionally you have to implement the two enaml funcs `previous_focus_child()` and `next_focus_child()` and define a chain of widgets that can receive the focus (see the focus_traversal.enaml example in the enaml repository under examples/widgets/).

Having the focus traversal feature implemented can still lead that widgets receiving the focus, e.g. when the user is clicking a button, that is not meant to receive focus. In this case you can either manually set the focus in the button press slot or alternatively one can set the focusEvent feature and move the focus within the `focus_gained()` enaml func.

Therefore I see no longer any need to implement the quite complex focusPolicy feature which is only supported by the Qt framework - KIS.

Thanks again for your great support/help and the enaml framework - closing this issue.
