### ISSUE TITLE
Support atom members in attr types

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#408]
It'd be nice to be able to have more explicit control of the type of an attr using an atom member.

Ex

```python
from atom.api import List

enamdef SomeWidget(Widget):
     attr items: List(int) = [1, 2, 3]

```

I assume it doesn't do this because parsing it becomes a mess?

**Comment by MatthieuDartiailh** [comment]
This would require special casing Atom members since currently a simple type check is performed.

**Comment by sccolbert** [comment]
It just needs to be a type. You can define your own type subclass with a
magic method that hooks the type-checking validation (I forget the magic
method name off the top of my head).

**Comment by frmdstryr** [comment]
`__instancecheck__` works but it seems like a hack compared to passing in a member.
