### ISSUE TITLE
cannot import enaml file if there is a python file with the same file name

### ISSUE THREAD

**Issue by AndiEcker** [nucleic/enaml#410]
Having a project with the files `main.py` and `main.enaml` or a extension package with the files names `package_folder/extension.enaml` and `package_folder/extension.py`, there is currently no way to import the enaml file.

With the few changes of PR #409 this would be possible.

And we should gain performance because (a) there is no longer any need to reverse the list of importers and (b) the remove of the reporters from `sys.meta_path` (on context exit) should also be faster because the items to remove are at the top of the `sys.meta_path`.

**Comment by frmdstryr** [comment]
What is `import main` from any other enaml file supposed to do when they both have the same module name? 

I think it's better to just not use two modules with the same name.

**Comment by MatthieuDartiailh** [comment]
I agree with @frmdstryr. Having different behavior in python and in enaml file is likely to create weird situations and the gain seems small to me (having written large enaml apps). 

An opinion @sccolbert ?

**Comment by sccolbert** [comment]
I’m -1 on this for the aforementioned reasons. Its also a needlessly breaking change.

Chris

**Comment by AndiEcker** [comment]
Thanks to all of you for your input and thoughts!!

Following your recommendations I will close this issue/PR. Closes #409, closes #410.

FYI: Just noticed that it is only working for local enaml/py modules. The other mentioned use case for packages is not working with the PR: trying to import within the enaml.imports() context the package/module.enaml will actually try to import the python module package/module.py.
