### ISSUE TITLE
Request: Add sublime text syntax package to sublime text package channel

### ISSUE THREAD

**Issue by AndydeCleyre** [nucleic/enaml#426]
Looking at https://packagecontrol.io/docs/submitting_a_package it seems the process could be something like:

- [x] Create new repo, e.g. `nucleic/enaml-sublimetext`
- [x] Copy `tools/sublimetext` content into new repo
- [x] Replace `tools/sublimetext` with a git submodule for the new repo
- [x] Tag the new repo with a semver
- [ ] Add to channel (steps 6, 7, 8)

**Comment by MatthieuDartiailh** [comment]
I will try to have a look in doing so but it may take me a while.  Do not hesitate to ping me.

**Comment by MatthieuDartiailh** [comment]
PR is at https://github.com/wbond/package_control_channel/pull/8095
