### ISSUE TITLE
Feature request: Grouping dock tabs into a dropdown

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#432]
It'd be nice if there was a way to push tabs into a dropdown once it runs out of space, like this

![img](https://raw.githubusercontent.com/githubuser0xFFFF/Qt-Advanced-Docking-System/master/doc/tab_menu.gif)

From https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System#tab-menu-for-easy-handling-of-many-tabbed-dock-widgets, is that a Qt thing or did they add that in?

Edit: Looks like they just add it to the title bar, https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/src/DockAreaTitleBar.cpp#L147

**Comment by sccolbert** [comment]
It looks like that person has just cloned Enaml's docking framework in C++
(with no acknowledgement or credit given) and added some things to it.
