### ISSUE TITLE
The example basic.enaml in examples/Templates There are some problem

### ISSUE THREAD

**Issue by zhaoxinmin** [nucleic/enaml#444]
the example Enaml/examples/templates/basic.enaml there are problems: OK | Cancel button click event doesn't work.That is, the 'Ok clicked！' or ’Cancel clicked’ information cannot be printed and no error message will appear on the console.

**Comment by MatthieuDartiailh** [comment]
Thanks for the report ! I can reproduce the issue and I will investigate it. Feel free to ping me if you do hear from me within a week.

**Comment by MatthieuDartiailh** [comment]
I opened a PR fixing the issue #445. I need to add tests before merging but the example works again.

**Comment by MatthieuDartiailh** [comment]
Closed by #445
