### ISSUE TITLE
Two questions regarding Enaml installation documention

### ISSUE THREAD

**Issue by gveneyjr** [nucleic/enaml#463]
Hi developers. I'm just getting started learning Enaml and was able to get the first getting started example running -- I'm quite impressed -- but two small things tripped me up I figured I'd let you know about:

1. The installation docs mention Python 3.6-3.8 as options, but not 3.9. The latter did in fact work for me and you have a commit mentioned adding support for 3.9 so probably just an oversight.
2. The documentation makes it seem as if you do not need `qtpy` if you install `pyqt5` but at least on MacOS I needed both.

I look forward to continuing with Enaml!

**Comment by MatthieuDartiailh** [comment]
Indeed it appears the docs have been lagging. The latest 0.14 supports 3.7 to 3.10. Qtpy is indeed always needed. Feel free to open a PR or will try to update the docs when I get some spare cycles.

**Comment by tstordyallison** [comment]
(also - it looks like the public docs are not building for some reason, so they still show 0.12.0: https://readthedocs.org/projects/enaml/builds/)

**Comment by MatthieuDartiailh** [comment]
Indeed it appears I forgot to handle the master -> main transition. Thanks @tstordyallison

**Comment by MatthieuDartiailh** [comment]
After some extra tinkering RTD is back on tracks ! Thanks again for reporting

**Comment by tstordyallison** [comment]
Nice, thanks for sorting so quick!
