### ISSUE TITLE
Using enaml just to invoke kiwisolver

### ISSUE THREAD

**Issue by maxme1** [nucleic/enaml#468]
Hi!

Is it possible to create a nested widgets structure (e.g. some Labels in a Container) in Python without `*.enaml` files and generate the coordinates and sizes for each widget? 

Basically, I am trying to render a static gui (without user interaction or resizing), and I would like to use kiwisolver to correctly position the widgets.

**Comment by sccolbert** [comment]
You can use kiwi without Enaml.

The layout helpers included with Enaml are pretty tightly coupled to the
Enaml widget hierarchy.

You could what you ask procedurally, but it would probably be less effort
to just use Kiwi directly.

**Comment by sccolbert** [comment]
I take that back. You might be able to create your own subclass of
Constrainable, and use that with Enaml’s layout helper functions. You would
just need to bootstrap your own Kiwi solver instance that solves the
constraints generated by the helpers.

**Comment by tstordyallison** [comment]
Or do you still actually want to use enaml just without the files (that is possible too)?

**Comment by maxme1** [comment]
> 

I found out [here](https://kiwisolver.readthedocs.io/en/latest/use_cases/enaml.html#setting-up-the-solver) that each Container already has a solver which is recursively invoked to solve the constraints for the tree. 
However, I couldn't find the solver in the class definition, nor how to provide my own solver a solve the constraints.

Also, I couldn't figure out how to create a Container which has some children. 
Neither `Container(children=[...])` nor 
```python
c = Container()
c.insert_children(None, [...])
```
seem to work.

I could implement my own widgets tree from scratch just by using `kiwisolver`, but `enaml` feels like a very promising framework for that.

**Comment by sccolbert** [comment]
Don’t give up so easy. You only spent like 20 minutes trying to “figure it
out”.

**Comment by maxme1** [comment]
I read all the docs from [here](https://kiwisolver.readthedocs.io), the relevant parts from [here](https://enaml.readthedocs.io) as well as parts of enaml's source code regarding the Container and Constrainable. 

I am sorry if my question is too basic, but some pointers or examples would be very helpful.

**Comment by maxme1** [comment]
I ended up generating python bindings for [yoga](https://github.com/facebook/yoga).
Thanks for your time though.
