### ISSUE TITLE
Mechanism to provide custom size hints

### ISSUE THREAD

**Issue by MatthieuDartiailh** [nucleic/enaml#473]
In some situation the toolkit provided size hint may be less than ideal. Matplotlib widgets are a perfect example of this as discussed on the mailing list: https://groups.google.com/d/msgid/enaml/CAPc_zRWYW0jUMP-m2YrYNmCihryV4Lgr_VUvJAQjQWM1gPU%2BGA%40mail.gmail.com?utm_medium=email&utm_source=footer

Providing a declarative way to override the toolkit size hint would be nice since the procedure to ignore the existing size hint based constraints and generating new ones is not trivial.

@sccolbert any take on the API we may want for this (attribute vs declarative method) ?

@bburan once we settle on an API I will try to implement the solution but since I have other enaml work that has been delayed a bit it may take some time. Feel free to make a PR yourself if you are so inclined.

**Comment by bburan** [comment]
@MatthieuDartiailh Happy to take a stab at implementing once we come up with the API. The `MainWindow` class does have an `initial_size` attribute which seems along the lines of what one might expect (e.g., add a `size_hint` option). What's the basis for deciding between an attribute vs. method in this case?

**Comment by sccolbert** [comment]
As far as attribute vs. method, making it a method would denote something
needs to be computed. Qt makes it a method, but you have access to
information like text measurement from which to compute a preferred size.
You won't have that at the Enaml level. Everything you compute would need
to be derived from information provided entirely from the Enaml side
(exposing the toolkit-provided size hint is probably impossible to make
work for a variety of reasons).

My first instinct would be to make it an attribute, but I could probably
drum up a use case for making it a method.

**Comment by MatthieuDartiailh** [comment]
Going for a method would allow to retrieve the toolkit hint and then adapt it. It would also allow to adjust the guess based on the parent content. In the case discussed in the mailing list, one could retrieve the number of plots in the grid to provide a better hint.

Also with an attribute I could see people expecting that updating the attribute would update the layout.

So personally I favor a method whose default implementation retrieves the toolkit hint.

**Comment by bburan** [comment]
A method does add flexibility and if all one wants to do is provide a size with no calculations, it's still fairly readable code, e.g.:
```
MPLContainer:
    size_hint => ():
        return (800, 400)
```
as opposed to:
```
MPLContainer:
    size_hint = (800, 400)
```

However, now that I better understand how to set up resit/hug and provide constraints, does adding a `size_hint` method add any additional value if one knows how to accomplish the same by setting constraints properly? If not, then I would be happy to submit a code example as an alternative (e.g., I could clean up and document the code example in this thread to add to the Enaml docs).

**Comment by MatthieuDartiailh** [comment]
Adding more examples around advanced layout techniques is likely worthwhile no matter what. I don't remember of the top of my head if we have examples dealing in details with hug and resist. I think I documented it at one point but I don't remember how deep I went.

I opened the issue since @sccolbert suggested that since it was a recurrent request it was worth adding a nicer way to do things.

**Comment by MatthieuDartiailh** [comment]
@bburan do you still plan a new example ?

**Comment by bburan** [comment]
@MatthieuDartiailh Thanks for checking in. Just submitted an example.

**Comment by MatthieuDartiailh** [comment]
Thanks
