### ISSUE TITLE
[DOC] How to use async/await function in Enaml ?

### ISSUE THREAD

**Issue by Kochise** [nucleic/enaml#510]
I'd like to use `async`/`await` functions and avoid blocking the UI.

Is there a "progress bar" available for pending operations ?

**Comment by MatthieuDartiailh** [comment]
There is a progress bar widget but I am not sure this what you are looking for. Using `qasync` you may be able to get what you want.

**Comment by Kochise** [comment]
`qasync` ?

**Comment by MatthieuDartiailh** [comment]
If you want to use `async / await` you need an asyncio compatible eventloop. `qasync` implement one on top of the Qt event loop.

**Comment by Kochise** [comment]
So not directly inside a `enaml` object ?

**Comment by MatthieuDartiailh** [comment]
You can write async func in an Enaml object. At one point you will need to start an asyncio.Task and this requires an asyncio event loop. @frmdstryr may be able to provide a more in depth description since he has been doing more work using async.

**Comment by Kochise** [comment]
Ok thank, looking forward to it.

**Comment by Kochise** [comment]
Works with `qasync`, thanks.

Closing...
