### ISSUE TITLE
Feature request: Allow const in enamldefs that uses the `ReadOnly` member

### ISSUE THREAD

**Issue by frmdstryr** [nucleic/enaml#545]
It would be nice to be able use `const` instead of a normal `attr` that uses a `Constant` member so the value can't be changed from the initial value. 

If you think this would be ok, I'd be willing to submit a PR.

**Comment by MatthieuDartiailh** [comment]
I will have to check how const is currently used. I am on my phone and could not remember/find what we do with it.

**Comment by sccolbert** [comment]
“const” is part of the templating system.

**Comment by sccolbert** [comment]
Yes, it has a purpose.

IIRC it is used to indicate expressions that are only evaluated once on the
first invocation of the template, and they cannot be changed later. Those
const values can then be used as parameters to specialize templates via
template overrides/specialization, very similar to C++.

You cannot pass a non-type, or non-const parameter to a template.

**Comment by sccolbert** [comment]
***first *unique* invocation of the template.

Template results are/should be cached based on their unique argument hash.
