### ISSUE TITLE
MenuBar-Action keyboard shortcuts for macOS

### ISSUE THREAD

**Issue by JefferyRPrice** [nucleic/enaml#551]
I cannot find a way to set appropriate keyboard shortcuts for Actions in a MenuBar on macOS (14.4.1). Simple source code based on the [Menu Bar Example](https://enaml.readthedocs.io/en/latest/examples/ex_menu_bar.html) is below. Have attached a screenshot showing the menu itself where the text is rendered, but not the keyboard shortcut. I tried the example `Ctrl-` and also a couple of more Mac-like things. Selecting the menu items manually works as expected, but I can't figure out how to make keyboard shortcuts work.

```
from enaml.widgets.api import Window, MenuBar, Menu, Action
enamldef Main(Window):
    title = 'MenuBarActions'

    MenuBar:
        Menu:
            title = 'Actions'
            Action:
                text = 'Trigger A\tCtrl-A'
                triggered :: print('A triggered')
            Action:
                text = 'Trigger B\tCmd-B'
                triggered :: print('B triggered')
            Action:
                text = 'Trigger C\tCommand-C'
                triggered :: print('C triggered')
```
<img width="408" alt="44" src="https://github.com/nucleic/enaml/assets/1270864/64c23baa-a799-4be1-a422-72f23dd32a28">

**Comment by MatthieuDartiailh** [comment]
If you look at the menu bar example you will notice it uses a `MainWindow` rather than a simple window. I do not remember the details of teh code well enough to be sure but can you check if the example using a `MainWindow` works and see if it can fix your issue ?

**Comment by JefferyRPrice** [comment]
I gave it a try with `MainWindow` instead of `Window` but got the same results.

**Comment by sccolbert** [comment]
IIRC you need to use a "+" character, instead of a "-" character in the
shortcut sequence.

**Comment by JefferyRPrice** [comment]
@sccolbert Yes, you are correct. I misread the tutorial page (that I linked originally) and used `Ctrl-` instead of `Ctrl+`.  

Once `Ctrl+` is used, things work largely as expected with either `Window` or `MainWindow`. On Mac, using `Ctrl+` generates menu actions with `Command` key instead of `Control`, but that's good behavior.

Apologies for the issue and appreciate your help!

<img width="332" alt="47" src="https://github.com/nucleic/enaml/assets/1270864/b2b83543-de5b-46d9-a143-2d0bb1518025">
